#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Maxiaofang_Special

#include "Basic.hpp"

#include "ABP_Maxiaofang_Special_classes.hpp"
#include "ABP_Maxiaofang_Special_parameters.hpp"


namespace SDK
{

// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.ExecuteUbergraph_ABP_Maxiaofang_Special
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Maxiaofang_Special_C::ExecuteUbergraph_ABP_Maxiaofang_Special(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "ExecuteUbergraph_ABP_Maxiaofang_Special");

	Params::ABP_Maxiaofang_Special_C_ExecuteUbergraph_ABP_Maxiaofang_Special Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.OnComponentStart
// (Event, Public, BlueprintEvent)

void UABP_Maxiaofang_Special_C::OnComponentStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "OnComponentStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Maxiaofang_Special_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "BlueprintUpdateAnimation");

	Params::ABP_Maxiaofang_Special_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_36EE3D65469C2F81A1D42C977BCA7F46
// (BlueprintEvent)

void UABP_Maxiaofang_Special_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_36EE3D65469C2F81A1D42C977BCA7F46()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_36EE3D65469C2F81A1D42C977BCA7F46");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_CCE9258F4D0E013EE4185AB2E49A8BC9
// (BlueprintEvent)

void UABP_Maxiaofang_Special_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_CCE9258F4D0E013EE4185AB2E49A8BC9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_CCE9258F4D0E013EE4185AB2E49A8BC9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_A4AAD93844234394BE4C2BBD79B3A6AC
// (BlueprintEvent)

void UABP_Maxiaofang_Special_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_A4AAD93844234394BE4C2BBD79B3A6AC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_A4AAD93844234394BE4C2BBD79B3A6AC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_355ADD324785F80F9BCAC8BFFEEEEC87
// (BlueprintEvent)

void UABP_Maxiaofang_Special_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_355ADD324785F80F9BCAC8BFFEEEEC87()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_355ADD324785F80F9BCAC8BFFEEEEC87");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_BlendListByBool_39BA8B484C1813CA51234D8DCB902C4E
// (BlueprintEvent)

void UABP_Maxiaofang_Special_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_BlendListByBool_39BA8B484C1813CA51234D8DCB902C4E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_BlendListByBool_39BA8B484C1813CA51234D8DCB902C4E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_MultiWayBlend_2061B8E84504E7E4B5F5E086352DFB10
// (BlueprintEvent)

void UABP_Maxiaofang_Special_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_MultiWayBlend_2061B8E84504E7E4B5F5E086352DFB10()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_MultiWayBlend_2061B8E84504E7E4B5F5E086352DFB10");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Maxiaofang_Special_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Maxiaofang_Special_C", "AnimGraph");

	Params::ABP_Maxiaofang_Special_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

