#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_R2T1YangyangMd10011_PC

#include "Basic.hpp"

#include "KuroAnim_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "KawaiiPhysics_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_R2T1YangyangMd10011_PC.ABP_R2T1YangyangMd10011_PC_C
// 0x1C60 (0x22C0 - 0x0660)
class UABP_R2T1YangyangMd10011_PC_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0660(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x0668(0x0038)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x06A0(0x0138)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x07D8(0x0020)()
	struct FAnimNode_MorphTargetModifier          AnimGraphNode_MorphTargetModifier;                 // 0x07F8(0x0060)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x0858(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0878(0x0038)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x08B0(0x0138)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x09E8(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0A08(0x0020)()
	uint8                                         Pad_A28[0x8];                                      // 0x0A28(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_MountBuffer                  AnimGraphNode_MountBuffer;                         // 0x0A30(0x01E0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_7;                // 0x0C10(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_6;                // 0x0EB0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_5;                // 0x1150(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_4;                // 0x13F0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_3;                // 0x1690(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_2;                // 0x1930(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_1;                // 0x1BD0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup;                  // 0x1E70(0x02A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x2110(0x0038)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x2148(0x00A8)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x21F0(0x00C0)()
	bool                                          PhysicsClothSimulateEnable;                        // 0x22B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_22B1[0x3];                                     // 0x22B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PhysicsClothSimulateScale;                         // 0x22B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ABP_R2T1YangyangMd10011_PC(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void UpdatePhysicsClothSimulateEnable(float DeltaTIme);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void PhyCloth(const struct FPoseLink& InPose, struct FPoseLink* PhyCloth_0);
	void MorphTargetModifier(const struct FPoseLink& InPose_0, struct FPoseLink* MorphTargetModifier_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_R2T1YangyangMd10011_PC_C">();
	}
	static class UABP_R2T1YangyangMd10011_PC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_R2T1YangyangMd10011_PC_C>();
	}
};
static_assert(alignof(UABP_R2T1YangyangMd10011_PC_C) == 0x000010, "Wrong alignment on UABP_R2T1YangyangMd10011_PC_C");
static_assert(sizeof(UABP_R2T1YangyangMd10011_PC_C) == 0x0022C0, "Wrong size on UABP_R2T1YangyangMd10011_PC_C");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, UberGraphFrame) == 0x000660, "Member 'UABP_R2T1YangyangMd10011_PC_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_Root_2) == 0x000668, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_LinkedInputPose_1) == 0x0006A0, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_LocalToComponentSpace_1) == 0x0007D8, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_MorphTargetModifier) == 0x0007F8, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_MorphTargetModifier' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x000858, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_Root_1) == 0x000878, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_LinkedInputPose) == 0x0008B0, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_LocalToComponentSpace) == 0x0009E8, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_ComponentToLocalSpace) == 0x000A08, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_MountBuffer) == 0x000A30, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_MountBuffer' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_7) == 0x000C10, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_7' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_6) == 0x000EB0, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_6' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_5) == 0x001150, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_5' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_4) == 0x0013F0, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_4' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_3) == 0x001690, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_3' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_2) == 0x001930, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_2' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup_1) == 0x001BD0, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup_1' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_KawaiiPhysicsGroup) == 0x001E70, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_KawaiiPhysicsGroup' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_Root) == 0x002110, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_LinkedAnimGraph) == 0x002148, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, AnimGraphNode_LinkedAnimLayer) == 0x0021F0, "Member 'UABP_R2T1YangyangMd10011_PC_C::AnimGraphNode_LinkedAnimLayer' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, PhysicsClothSimulateEnable) == 0x0022B0, "Member 'UABP_R2T1YangyangMd10011_PC_C::PhysicsClothSimulateEnable' has a wrong offset!");
static_assert(offsetof(UABP_R2T1YangyangMd10011_PC_C, PhysicsClothSimulateScale) == 0x0022B4, "Member 'UABP_R2T1YangyangMd10011_PC_C::PhysicsClothSimulateScale' has a wrong offset!");

}

