#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Maxiaofang_Special

#include "Basic.hpp"

#include "KuroAnim_structs.hpp"
#include "KuroAnim_classes.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Maxiaofang_Special.ABP_Maxiaofang_Special_C
// 0x18E0 (0x2030 - 0x0750)
class UABP_Maxiaofang_Special_C final : public UKuroAnimInstance
{
public:
	uint8                                         Pad_748[0x8];                                      // 0x0748(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0750(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0758(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x0790(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x07B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x07E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x0808(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0830(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0858(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0880(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x08A8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x0938(0x0038)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_4;                     // 0x0970(0x00D8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0A48(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0AD8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x0B68(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0BA0(0x0090)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x0C30(0x00F8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x0D28(0x0090)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_3;                     // 0x0DB8(0x00D8)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x0E90(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x0F58(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x0FE8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1078(0x0090)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x1108(0x00C0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x11C8(0x0090)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend;                       // 0x1258(0x0050)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x12A8(0x00B0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x1358(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x13E8(0x0090)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_2;                     // 0x1478(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x1550(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1588(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1618(0x0090)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x16A8(0x00C8)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x1770(0x00C0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x1830(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x18C0(0x0090)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_1;                     // 0x1950(0x00D8)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x1A28(0x00D8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x1B00(0x00F8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x1BF8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x1C30(0x0148)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x1D78(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x1DB0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x1DD8(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x1E68(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x1EA0(0x0148)()
	bool                                          技能状态_移动射击技能持续;                         // 0x1FE8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1FE9[0x7];                                     // 0x1FE9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UABP_BaseRole_C*                        BaseRole;                                          // 0x1FF0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         瞄准仰角;                                          // 0x1FF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMoveDirection                                移动方向;                                          // 0x1FFC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FFD[0x3];                                     // 0x1FFD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVeloctiyBlend                         速度混合;                                          // 0x2000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         下落速度;                                          // 0x2010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         空中_目标角度;                                     // 0x2014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          技能状态_移动射击;                                 // 0x2018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_空中瞄准;                                 // 0x2019(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_空中普攻发射;                             // 0x201A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_空中普攻结束;                             // 0x201B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_空中前6帧蓄力判断;                        // 0x201C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_提前落地翻滚;                             // 0x201D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_提前落地缓冲;                             // 0x201E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          技能状态_空中瞄准射击;                             // 0x201F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         速度;                                              // 0x2020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          技能状态_注视方向;                                 // 0x2024(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_Maxiaofang_Special(int32 EntryPoint);
	void OnComponentStart();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_36EE3D65469C2F81A1D42C977BCA7F46();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_CCE9258F4D0E013EE4185AB2E49A8BC9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_A4AAD93844234394BE4C2BBD79B3A6AC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_TransitionResult_355ADD324785F80F9BCAC8BFFEEEEC87();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_BlendListByBool_39BA8B484C1813CA51234D8DCB902C4E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Maxiaofang_Special_AnimGraphNode_MultiWayBlend_2061B8E84504E7E4B5F5E086352DFB10();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Maxiaofang_Special_C">();
	}
	static class UABP_Maxiaofang_Special_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Maxiaofang_Special_C>();
	}
};
static_assert(alignof(UABP_Maxiaofang_Special_C) == 0x000010, "Wrong alignment on UABP_Maxiaofang_Special_C");
static_assert(sizeof(UABP_Maxiaofang_Special_C) == 0x002030, "Wrong size on UABP_Maxiaofang_Special_C");
static_assert(offsetof(UABP_Maxiaofang_Special_C, UberGraphFrame) == 0x000750, "Member 'UABP_Maxiaofang_Special_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_Root) == 0x000758, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_7) == 0x000790, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_6) == 0x0007B8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_5) == 0x0007E0, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_4) == 0x000808, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_3) == 0x000830, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_2) == 0x000858, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult_1) == 0x000880, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_15) == 0x0008A8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateResult_5) == 0x000938, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_ApplyAdditive_4) == 0x000970, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_ApplyAdditive_4' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_14) == 0x000A48, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_13) == 0x000AD8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateResult_4) == 0x000B68, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_12) == 0x000BA0, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_BlendSpacePlayer_1) == 0x000C30, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_11) == 0x000D28, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_ApplyAdditive_3) == 0x000DB8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_ApplyAdditive_3' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TwoWayBlend_1) == 0x000E90, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TwoWayBlend_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_10) == 0x000F58, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_9) == 0x000FE8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_8) == 0x001078, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_LayeredBoneBlend_1) == 0x001108, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_7) == 0x0011C8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_MultiWayBlend) == 0x001258, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_MultiWayBlend' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_BlendListByBool) == 0x0012A8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_6) == 0x001358, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_5) == 0x0013E8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_ApplyAdditive_2) == 0x001478, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_ApplyAdditive_2' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateResult_3) == 0x001550, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_4) == 0x001588, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_3) == 0x001618, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TwoWayBlend) == 0x0016A8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_LayeredBoneBlend) == 0x001770, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_2) == 0x001830, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer_1) == 0x0018C0, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_ApplyAdditive_1) == 0x001950, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_ApplyAdditive_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_ApplyAdditive) == 0x001A28, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_BlendSpacePlayer) == 0x001B00, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateResult_2) == 0x001BF8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateMachine_1) == 0x001C30, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateResult_1) == 0x001D78, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_TransitionResult) == 0x001DB0, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_SequencePlayer) == 0x001DD8, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateResult) == 0x001E68, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, AnimGraphNode_StateMachine) == 0x001EA0, "Member 'UABP_Maxiaofang_Special_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_移动射击技能持续) == 0x001FE8, "Member 'UABP_Maxiaofang_Special_C::技能状态_移动射击技能持续' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, BaseRole) == 0x001FF0, "Member 'UABP_Maxiaofang_Special_C::BaseRole' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 瞄准仰角) == 0x001FF8, "Member 'UABP_Maxiaofang_Special_C::瞄准仰角' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 移动方向) == 0x001FFC, "Member 'UABP_Maxiaofang_Special_C::移动方向' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 速度混合) == 0x002000, "Member 'UABP_Maxiaofang_Special_C::速度混合' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 下落速度) == 0x002010, "Member 'UABP_Maxiaofang_Special_C::下落速度' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 空中_目标角度) == 0x002014, "Member 'UABP_Maxiaofang_Special_C::空中_目标角度' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_移动射击) == 0x002018, "Member 'UABP_Maxiaofang_Special_C::技能状态_移动射击' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_空中瞄准) == 0x002019, "Member 'UABP_Maxiaofang_Special_C::技能状态_空中瞄准' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_空中普攻发射) == 0x00201A, "Member 'UABP_Maxiaofang_Special_C::技能状态_空中普攻发射' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_空中普攻结束) == 0x00201B, "Member 'UABP_Maxiaofang_Special_C::技能状态_空中普攻结束' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_空中前6帧蓄力判断) == 0x00201C, "Member 'UABP_Maxiaofang_Special_C::技能状态_空中前6帧蓄力判断' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_提前落地翻滚) == 0x00201D, "Member 'UABP_Maxiaofang_Special_C::技能状态_提前落地翻滚' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_提前落地缓冲) == 0x00201E, "Member 'UABP_Maxiaofang_Special_C::技能状态_提前落地缓冲' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_空中瞄准射击) == 0x00201F, "Member 'UABP_Maxiaofang_Special_C::技能状态_空中瞄准射击' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 速度) == 0x002020, "Member 'UABP_Maxiaofang_Special_C::速度' has a wrong offset!");
static_assert(offsetof(UABP_Maxiaofang_Special_C, 技能状态_注视方向) == 0x002024, "Member 'UABP_Maxiaofang_Special_C::技能状态_注视方向' has a wrong offset!");

}

