#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Lingyang_NPC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "KawaiiPhysics_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Lingyang_NPC.ABP_Lingyang_NPC_C
// 0x22E0 (0x2940 - 0x0660)
class UABP_Lingyang_NPC_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0660(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0668(0x0038)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x06A0(0x0138)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x07D8(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x07F8(0x0020)()
	uint8                                         Pad_818[0x8];                                      // 0x0818(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_11;               // 0x0820(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_10;               // 0x0AC0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_9;                // 0x0D60(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_8;                // 0x1000(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_7;                // 0x12A0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_6;                // 0x1540(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_5;                // 0x17E0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_4;                // 0x1A80(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_3;                // 0x1D20(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_2;                // 0x1FC0(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup_1;                // 0x2260(0x02A0)()
	struct FAnimNode_KawaiiPhysicsGroup           AnimGraphNode_KawaiiPhysicsGroup;                  // 0x2500(0x02A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x27A0(0x0038)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x27D8(0x00C0)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x2898(0x00A8)()

public:
	void ExecuteUbergraph_ABP_Lingyang_NPC(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void PhyCloth(const struct FPoseLink& InPose, struct FPoseLink* PhyCloth_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Lingyang_NPC_C">();
	}
	static class UABP_Lingyang_NPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Lingyang_NPC_C>();
	}
};
static_assert(alignof(UABP_Lingyang_NPC_C) == 0x000010, "Wrong alignment on UABP_Lingyang_NPC_C");
static_assert(sizeof(UABP_Lingyang_NPC_C) == 0x002940, "Wrong size on UABP_Lingyang_NPC_C");
static_assert(offsetof(UABP_Lingyang_NPC_C, UberGraphFrame) == 0x000660, "Member 'UABP_Lingyang_NPC_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_Root_1) == 0x000668, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_LinkedInputPose) == 0x0006A0, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_LocalToComponentSpace) == 0x0007D8, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_ComponentToLocalSpace) == 0x0007F8, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_11) == 0x000820, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_11' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_10) == 0x000AC0, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_10' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_9) == 0x000D60, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_9' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_8) == 0x001000, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_8' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_7) == 0x0012A0, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_7' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_6) == 0x001540, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_6' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_5) == 0x0017E0, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_5' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_4) == 0x001A80, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_4' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_3) == 0x001D20, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_3' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_2) == 0x001FC0, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_2' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup_1) == 0x002260, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup_1' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_KawaiiPhysicsGroup) == 0x002500, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_KawaiiPhysicsGroup' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_Root) == 0x0027A0, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_LinkedAnimLayer) == 0x0027D8, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_LinkedAnimLayer' has a wrong offset!");
static_assert(offsetof(UABP_Lingyang_NPC_C, AnimGraphNode_LinkedAnimGraph) == 0x002898, "Member 'UABP_Lingyang_NPC_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");

}

