#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_BaseRoleNPC

#include "Basic.hpp"

#include "ABP_BaseRoleNPC_classes.hpp"
#include "ABP_BaseRoleNPC_parameters.hpp"


namespace SDK
{

// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.ExecuteUbergraph_ABP_BaseRoleNPC
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_BaseRoleNPC_C::ExecuteUbergraph_ABP_BaseRoleNPC(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "ExecuteUbergraph_ABP_BaseRoleNPC");

	Params::ABP_BaseRoleNPC_C_ExecuteUbergraph_ABP_BaseRoleNPC Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.MovementChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMovementMode                           PrevMovementMode                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   PreviousCustomMode                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_BaseRoleNPC_C::MovementChanged(class ACharacter* Character, EMovementMode PrevMovementMode, uint8 PreviousCustomMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "MovementChanged");

	Params::ABP_BaseRoleNPC_C_MovementChanged Parms{};

	Parms.Character = Character;
	Parms.PrevMovementMode = PrevMovementMode;
	Parms.PreviousCustomMode = PreviousCustomMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.OnComponentStart
// (Event, Public, BlueprintEvent)

void UABP_BaseRoleNPC_C::OnComponentStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "OnComponentStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.AnimNotify_停止动画
// (BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::AnimNotify_停止动画()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "AnimNotify_停止动画");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.播放动画
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSDynamicMontageParams&    播放动画_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_BaseRoleNPC_C::播放动画(const struct FSDynamicMontageParams& 播放动画_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "播放动画");

	Params::ABP_BaseRoleNPC_C_播放动画 Parms{};

	Parms.播放动画_0 = std::move(播放动画_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_BaseRoleNPC_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_BaseRoleNPC_C::BlueprintUpdateAnimation(float DeltaTimeX_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "BlueprintUpdateAnimation");

	Params::ABP_BaseRoleNPC_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX_0 = DeltaTimeX_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3E404ABF415A86DE760E4EA5D518A11A
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3E404ABF415A86DE760E4EA5D518A11A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3E404ABF415A86DE760E4EA5D518A11A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3CFDE6C94309141C64E2ED8B06C1F1D6
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3CFDE6C94309141C64E2ED8B06C1F1D6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3CFDE6C94309141C64E2ED8B06C1F1D6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9397B12D44E48C5E1B6EE1B0605E64B1
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9397B12D44E48C5E1B6EE1B0605E64B1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9397B12D44E48C5E1B6EE1B0605E64B1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_ModifyBone_2FDA046645AE9155BEEEFB9E86DDDB38
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_ModifyBone_2FDA046645AE9155BEEEFB9E86DDDB38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_ModifyBone_2FDA046645AE9155BEEEFB9E86DDDB38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_D7667F094E190371575D33A294CA0593
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_D7667F094E190371575D33A294CA0593()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_D7667F094E190371575D33A294CA0593");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_12D5B63A43BEA91A69FF3D9E09D44913
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_12D5B63A43BEA91A69FF3D9E09D44913()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_12D5B63A43BEA91A69FF3D9E09D44913");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_71EC0ADC497DCA9F71FA849635BAA6FF
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_71EC0ADC497DCA9F71FA849635BAA6FF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_71EC0ADC497DCA9F71FA849635BAA6FF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_37283ACE4757CBE458A8DCACAC8384FA
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_37283ACE4757CBE458A8DCACAC8384FA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_37283ACE4757CBE458A8DCACAC8384FA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_54C0791143921BB0C2145DB52A2D1E7D
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_54C0791143921BB0C2145DB52A2D1E7D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_54C0791143921BB0C2145DB52A2D1E7D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_2BA72E324A2C3755C78022B557F6A491
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_2BA72E324A2C3755C78022B557F6A491()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_2BA72E324A2C3755C78022B557F6A491");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_75CC77F6411E288DF118E4A64360A8A1
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_75CC77F6411E288DF118E4A64360A8A1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_75CC77F6411E288DF118E4A64360A8A1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_25D5D6714880F255FC261BBF86F6D527
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_25D5D6714880F255FC261BBF86F6D527()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_25D5D6714880F255FC261BBF86F6D527");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_5CB65EF244800BD2D7264B96580C906B
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_5CB65EF244800BD2D7264B96580C906B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_5CB65EF244800BD2D7264B96580C906B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_72DFAFBE41537440C4759AB2D3F29556
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_72DFAFBE41537440C4759AB2D3F29556()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_72DFAFBE41537440C4759AB2D3F29556");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DACFF3464D3F9AB8436B12A8C3BC8B5F
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DACFF3464D3F9AB8436B12A8C3BC8B5F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_DACFF3464D3F9AB8436B12A8C3BC8B5F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_41429680472D043A4766F2B4A3547DF9
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_41429680472D043A4766F2B4A3547DF9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_41429680472D043A4766F2B4A3547DF9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_482074B940ABF6ECD1CD999E796EA34E
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_482074B940ABF6ECD1CD999E796EA34E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_482074B940ABF6ECD1CD999E796EA34E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FB54B9D43E2572F934764B89525DBA6
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FB54B9D43E2572F934764B89525DBA6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FB54B9D43E2572F934764B89525DBA6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_697CCA5F461EB64F0A5995B7AB953813
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_697CCA5F461EB64F0A5995B7AB953813()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_697CCA5F461EB64F0A5995B7AB953813");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_15F4BF374115C55BAF6DE084E8329BAD
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_15F4BF374115C55BAF6DE084E8329BAD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_15F4BF374115C55BAF6DE084E8329BAD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_8A9A74574D3EFAD95B682B9762D628A4
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_8A9A74574D3EFAD95B682B9762D628A4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_8A9A74574D3EFAD95B682B9762D628A4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F57C68684C60238886A3D9B21095676D
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F57C68684C60238886A3D9B21095676D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F57C68684C60238886A3D9B21095676D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9F27C0544AD432DD916ECCAD79037483
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9F27C0544AD432DD916ECCAD79037483()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_9F27C0544AD432DD916ECCAD79037483");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F1EE968D4C35EBE8858ADCA296615B8B
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F1EE968D4C35EBE8858ADCA296615B8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F1EE968D4C35EBE8858ADCA296615B8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0A26E7433EB47953A74BB9150A949B
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0A26E7433EB47953A74BB9150A949B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0A26E7433EB47953A74BB9150A949B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_1EBE3AB24D1188D2CA1DD28F1DACFE80
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_1EBE3AB24D1188D2CA1DD28F1DACFE80()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_1EBE3AB24D1188D2CA1DD28F1DACFE80");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_0BFF18DF40B3D7DAE87832B09238CB8C
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_0BFF18DF40B3D7DAE87832B09238CB8C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_0BFF18DF40B3D7DAE87832B09238CB8C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F811B7054E27C606851206B15100569C
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F811B7054E27C606851206B15100569C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F811B7054E27C606851206B15100569C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0F9EE5494DF8709F1B6EAD85AB61B6
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0F9EE5494DF8709F1B6EAD85AB61B6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BB0F9EE5494DF8709F1B6EAD85AB61B6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_4C84D2A14F534CE2478E7FA4196612A8
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_4C84D2A14F534CE2478E7FA4196612A8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_4C84D2A14F534CE2478E7FA4196612A8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_946C1FB64468DEB2922F3DB47CA0F108
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_946C1FB64468DEB2922F3DB47CA0F108()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_946C1FB64468DEB2922F3DB47CA0F108");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FBACAF34017F5002FD261897498FDB9
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FBACAF34017F5002FD261897498FDB9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_3FBACAF34017F5002FD261897498FDB9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F872E4934C5985382E8C969E69266422
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F872E4934C5985382E8C969E69266422()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_F872E4934C5985382E8C969E69266422");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BEEE3BFE494E3CEB5727B3854D1404D5
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BEEE3BFE494E3CEB5727B3854D1404D5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_BEEE3BFE494E3CEB5727B3854D1404D5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_23664840422729DF8D8A68B2DDD8DBDC
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_23664840422729DF8D8A68B2DDD8DBDC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_23664840422729DF8D8A68B2DDD8DBDC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_34726529440463E15F0244939A7F18B5
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_34726529440463E15F0244939A7F18B5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_TransitionResult_34726529440463E15F0244939A7F18B5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_KuroHumanIK_36C2723F47E5A6C9D004AD9A68AF8A17
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_KuroHumanIK_36C2723F47E5A6C9D004AD9A68AF8A17()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_KuroHumanIK_36C2723F47E5A6C9D004AD9A68AF8A17");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_CombineCurves_F94882F047B8D7B2DE316584D85149DC
// (BlueprintEvent)

void UABP_BaseRoleNPC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_CombineCurves_F94882F047B8D7B2DE316584D85149DC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_BaseRoleNPC_AnimGraphNode_CombineCurves_F94882F047B8D7B2DE316584D85149DC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.是否需要移动
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UABP_BaseRoleNPC_C::是否需要移动()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "是否需要移动");

	Params::ABP_BaseRoleNPC_C_是否需要移动 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新旋转信息
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新旋转信息()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新旋转信息");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.原地旋转检查
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::原地旋转检查()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "原地旋转检查");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新 IK信息
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新_IK信息()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新 IK信息");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新头部转向
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UABP_BaseRoleNPC_C::更新头部转向(const struct FRotator& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新头部转向");

	Params::ABP_BaseRoleNPC_C_更新头部转向 Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.设置头部转向状态
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESightLockMode                          SightMode                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_BaseRoleNPC_C::设置头部转向状态(ESightLockMode SightMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "设置头部转向状态");

	Params::ABP_BaseRoleNPC_C_设置头部转向状态 Parms{};

	Parms.SightMode = SightMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新角色状态
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新角色状态()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新角色状态");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新随机表演
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新随机表演()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新随机表演");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新移动组件参数
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新移动组件参数()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新移动组件参数");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新动画组件参数
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新动画组件参数()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新动画组件参数");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新网络参数
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新网络参数()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新网络参数");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新时间参数
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新时间参数()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新时间参数");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新上传
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新上传()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新上传");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.切换地面移动模式时高度补差
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::切换地面移动模式时高度补差()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "切换地面移动模式时高度补差");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新状态参数信息
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新状态参数信息()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新状态参数信息");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新角色信息
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新角色信息()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新角色信息");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新移动信息
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新移动信息()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新移动信息");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.绑定组件参数
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::绑定组件参数()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "绑定组件参数");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.组件参数动画蓝图初始化绑定
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::组件参数动画蓝图初始化绑定()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "组件参数动画蓝图初始化绑定");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.初始化身高
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::初始化身高()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "初始化身高");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.更新载具信息
// (Public, BlueprintCallable, BlueprintEvent)

void UABP_BaseRoleNPC_C::更新载具信息()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "更新载具信息");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_BaseRoleNPC.ABP_BaseRoleNPC_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_BaseRoleNPC_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_BaseRoleNPC_C", "AnimGraph");

	Params::ABP_BaseRoleNPC_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

