#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_NH_FemaleM_Base_Simple

#include "Basic.hpp"

#include "ABP_SimpleNPC_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_NH_FemaleM_Base_Simple.ABP_NH_FemaleM_Base_Simple_C
// 0x0000 (0x1920 - 0x1920)
class UABP_NH_FemaleM_Base_Simple_C final : public UABP_SimpleNPC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_NH_FemaleM_Base_Simple_C">();
	}
	static class UABP_NH_FemaleM_Base_Simple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_NH_FemaleM_Base_Simple_C>();
	}
};
static_assert(alignof(UABP_NH_FemaleM_Base_Simple_C) == 0x000010, "Wrong alignment on UABP_NH_FemaleM_Base_Simple_C");
static_assert(sizeof(UABP_NH_FemaleM_Base_Simple_C) == 0x001920, "Wrong size on UABP_NH_FemaleM_Base_Simple_C");

}

