#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Input_Anke

#include "Basic.hpp"

#include "sInputCommand_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function BP_Input_Anke.BP_Input_Anke_C.攻击按下
// 0x02A0 (0x02A0 - 0x0000)
struct BP_Input_Anke_C_攻击按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_True_if_break_was_hit_Variable;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc______ReturnValue;                         // 0x001C(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Variable;                                   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Loop_Counter_Variable;                      // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Array_Index_Variable;                       // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSkillAcceptInput_ReturnValue;          // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_46[0x2];                                       // 0x0046(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0048(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSkillAcceptInput_ReturnValue_1;        // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue; // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5E[0x2];                                       // 0x005E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Array_Index_Variable_1;                     // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_1;                                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x0068(0x0020)()
	TArray<struct FGameplayTag>                   CallFunc_BreakGameplayTagContainer_GameplayTags;   // 0x0088(0x0010)(ReferenceParm)
	struct FGameplayTag                           CallFunc_Array_Get_Item;                           // 0x0098(0x000C)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00A7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_True_if_break_was_hit_Variable_1;          // 0x00AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x00AE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AF[0x1];                                       // 0x00AF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x00B0(0x0014)(NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable_2;                                 // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_2;         // 0x00C8(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_3;         // 0x00DC(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSkillAcceptInput_ReturnValue_2;        // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x00F8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue_1; // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x010A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10B[0x1];                                      // 0x010B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_4;         // 0x010C(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_5;         // 0x0120(0x0014)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_1; // 0x0138(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_1;     // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x3];                                      // 0x0149(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Variable_3;                                 // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_2; // 0x0150(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_2;     // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue_1; // 0x0168(0x0020)()
	TArray<struct FGameplayTag>                   CallFunc_BreakGameplayTagContainer_GameplayTags_1; // 0x0188(0x0010)(ReferenceParm)
	struct FGameplayTag                           CallFunc_Array_Get_Item_1;                         // 0x0198(0x000C)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_3; // 0x01A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_3;     // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x01BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1BB[0x5];                                      // 0x01BB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 K2Node_MakeArray_Array;                            // 0x01C0(0x0010)(ReferenceParm)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_6;         // 0x01D0(0x0014)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Get_Item_2;                         // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_4; // 0x01F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_4;     // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_5; // 0x0208(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_5;     // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_219[0x3];                                      // 0x0219(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_7;         // 0x021C(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_8;         // 0x0230(0x0014)(NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Loop_Counter_Variable_1;                    // 0x0244(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_249[0x3];                                      // 0x0249(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 K2Node_MakeArray_Array_1;                          // 0x0258(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Get_Item_3;                         // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26C[0x4];                                      // 0x026C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_6; // 0x0270(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_6;     // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_1;         // 0x0281(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_282[0x6];                                      // 0x0282(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_7; // 0x0288(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_7;     // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Anke_C_攻击按下) == 0x000008, "Wrong alignment on BP_Input_Anke_C_攻击按下");
static_assert(sizeof(BP_Input_Anke_C_攻击按下) == 0x0002A0, "Wrong size on BP_Input_Anke_C_攻击按下");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, time) == 0x000000, "Member 'BP_Input_Anke_C_攻击按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ReturnValue) == 0x000004, "Member 'BP_Input_Anke_C_攻击按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___bool_True_if_break_was_hit_Variable) == 0x000018, "Member 'BP_Input_Anke_C_攻击按下::___bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc______ReturnValue) == 0x00001C, "Member 'BP_Input_Anke_C_攻击按下::CallFunc______ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Not_PreBool_ReturnValue) == 0x000030, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Variable) == 0x000034, "Member 'BP_Input_Anke_C_攻击按下::___int_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Loop_Counter_Variable) == 0x000038, "Member 'BP_Input_Anke_C_攻击按下::___int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Add_IntInt_ReturnValue) == 0x00003C, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Array_Index_Variable) == 0x000040, "Member 'BP_Input_Anke_C_攻击按下::___int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_GetSkillAcceptInput_ReturnValue) == 0x000044, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_GetSkillAcceptInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CanResponseInput_ReturnValue) == 0x000045, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x000048, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_GetSkillAcceptInput_ReturnValue_1) == 0x00005C, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_GetSkillAcceptInput_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue) == 0x00005D, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Array_Index_Variable_1) == 0x000060, "Member 'BP_Input_Anke_C_攻击按下::___int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Variable_1) == 0x000064, "Member 'BP_Input_Anke_C_攻击按下::___int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x000068, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BreakGameplayTagContainer_GameplayTags) == 0x000088, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BreakGameplayTagContainer_GameplayTags' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_Get_Item) == 0x000098, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000A4, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0000A5, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x0000A6, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BooleanAND_ReturnValue) == 0x0000A7, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_Length_ReturnValue) == 0x0000A8, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BooleanOR_ReturnValue) == 0x0000AC, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___bool_True_if_break_was_hit_Variable_1) == 0x0000AD, "Member 'BP_Input_Anke_C_攻击按下::___bool_True_if_break_was_hit_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Not_PreBool_ReturnValue_1) == 0x0000AE, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x0000B0, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Variable_2) == 0x0000C4, "Member 'BP_Input_Anke_C_攻击按下::___int_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_2) == 0x0000C8, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_3) == 0x0000DC, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_GetSkillAcceptInput_ReturnValue_2) == 0x0000F0, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_GetSkillAcceptInput_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x0000F8, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000108, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue_1) == 0x000109, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BooleanOR_ReturnValue_1) == 0x00010A, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_4) == 0x00010C, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_5) == 0x000120, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_1) == 0x000138, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_1) == 0x000148, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Variable_3) == 0x00014C, "Member 'BP_Input_Anke_C_攻击按下::___int_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_2) == 0x000150, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_2) == 0x000160, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue_1) == 0x000168, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BreakGameplayTagContainer_GameplayTags_1) == 0x000188, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BreakGameplayTagContainer_GameplayTags_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_Get_Item_1) == 0x000198, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_Length_ReturnValue_1) == 0x0001A4, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_3) == 0x0001A8, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_3) == 0x0001B8, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Less_IntInt_ReturnValue) == 0x0001B9, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BooleanAND_ReturnValue_1) == 0x0001BA, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, K2Node_MakeArray_Array) == 0x0001C0, "Member 'BP_Input_Anke_C_攻击按下::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_6) == 0x0001D0, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_Get_Item_2) == 0x0001E4, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_IsValidIndex_ReturnValue) == 0x0001E8, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_4) == 0x0001F0, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_4) == 0x000200, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_5) == 0x000208, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_5) == 0x000218, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_7) == 0x00021C, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_8) == 0x000230, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, ___int_Loop_Counter_Variable_1) == 0x000244, "Member 'BP_Input_Anke_C_攻击按下::___int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Less_IntInt_ReturnValue_1) == 0x000248, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Add_IntInt_ReturnValue_1) == 0x00024C, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_BooleanAND_ReturnValue_2) == 0x000250, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, K2Node_MakeArray_Array_1) == 0x000258, "Member 'BP_Input_Anke_C_攻击按下::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_Get_Item_3) == 0x000268, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_6) == 0x000270, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_6) == 0x000280, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_Array_IsValidIndex_ReturnValue_1) == 0x000281, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_Array_IsValidIndex_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_7) == 0x000288, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_7' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_7) == 0x000298, "Member 'BP_Input_Anke_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_7' has a wrong offset!");

// Function BP_Input_Anke.BP_Input_Anke_C.攻击长按
// 0x00F0 (0x00F0 - 0x0000)
struct BP_Input_Anke_C_攻击长按 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc______ReturnValue;                         // 0x0018(0x0014)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue;     // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0030(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue_1;   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue_2;   // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSkillAcceptInput_ReturnValue;          // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue; // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x0054(0x0014)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue_3;   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x0070(0x0020)()
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_1;    // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasAnyMatchingGameplayTags_self_CastInput; // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAnyMatchingGameplayTags_ReturnValue;   // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x00AA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00AB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_2;         // 0x00B0(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_3;         // 0x00C4(0x0014)(NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x00D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Anke_C_攻击长按) == 0x000008, "Wrong alignment on BP_Input_Anke_C_攻击长按");
static_assert(sizeof(BP_Input_Anke_C_攻击长按) == 0x0000F0, "Wrong size on BP_Input_Anke_C_攻击长按");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, time) == 0x000000, "Member 'BP_Input_Anke_C_攻击长按::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, ReturnValue) == 0x000004, "Member 'BP_Input_Anke_C_攻击长按::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc______ReturnValue) == 0x000018, "Member 'BP_Input_Anke_C_攻击长按::CallFunc______ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GetAttributeCurrentValue_ReturnValue) == 0x00002C, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GetAttributeCurrentValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_CreateSkillCommand_ReturnValue) == 0x000030, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_CanResponseInput_ReturnValue) == 0x000044, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GetAttributeCurrentValue_ReturnValue_1) == 0x000048, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GetAttributeCurrentValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GetAttributeCurrentValue_ReturnValue_2) == 0x00004C, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GetAttributeCurrentValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000050, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GetSkillAcceptInput_ReturnValue) == 0x000051, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GetSkillAcceptInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue) == 0x000052, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_BooleanOR_ReturnValue) == 0x000053, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x000054, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GetAttributeCurrentValue_ReturnValue_3) == 0x000068, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GetAttributeCurrentValue_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x000070, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_GreaterEqual_FloatFloat_ReturnValue_1) == 0x000090, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_GreaterEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000091, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_HasAnyMatchingGameplayTags_self_CastInput) == 0x000098, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_HasAnyMatchingGameplayTags_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_HasAnyMatchingGameplayTags_ReturnValue) == 0x0000A8, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_HasAnyMatchingGameplayTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0000A9, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_IsMovingOnGround_ReturnValue) == 0x0000AA, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_BooleanAND_ReturnValue) == 0x0000AB, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_BooleanOR_ReturnValue_1) == 0x0000AC, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_CreateSkillCommand_ReturnValue_2) == 0x0000B0, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_CreateSkillCommand_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_CreateSkillCommand_ReturnValue_3) == 0x0000C4, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_CreateSkillCommand_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x0000D8, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_攻击长按, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x0000E8, "Member 'BP_Input_Anke_C_攻击长按::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");

// Function BP_Input_Anke.BP_Input_Anke_C.攻击抬起事件
// 0x0004 (0x0004 - 0x0000)
struct BP_Input_Anke_C_攻击抬起事件 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Input_Anke_C_攻击抬起事件) == 0x000004, "Wrong alignment on BP_Input_Anke_C_攻击抬起事件");
static_assert(sizeof(BP_Input_Anke_C_攻击抬起事件) == 0x000004, "Wrong size on BP_Input_Anke_C_攻击抬起事件");
static_assert(offsetof(BP_Input_Anke_C_攻击抬起事件, time) == 0x000000, "Member 'BP_Input_Anke_C_攻击抬起事件::time' has a wrong offset!");

// Function BP_Input_Anke.BP_Input_Anke_C.技能1按下
// 0x01A8 (0x01A8 - 0x0000)
struct BP_Input_Anke_C_技能1按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc___1___ReturnValue;                        // 0x0018(0x0014)(NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable;                                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0030(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x0044(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_True_if_break_was_hit_Variable;            // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_2;         // 0x005C(0x0014)(NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Loop_Counter_Variable;                      // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0078(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x008B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         ___int_Variable_1;                                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x2];                                       // 0x0092(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Array_Index_Variable;                       // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_1; // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_1;     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x00B0(0x0020)()
	TArray<struct FGameplayTag>                   CallFunc_BreakGameplayTagContainer_GameplayTags;   // 0x00D0(0x0010)(ReferenceParm)
	struct FGameplayTag                           CallFunc_Array_Get_Item;                           // 0x00E0(0x000C)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_2; // 0x00F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_2;     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x3];                                      // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10A[0x2];                                      // 0x010A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_3;         // 0x010C(0x0014)(NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_3; // 0x0120(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_3;     // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0x3];                                      // 0x0131(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_4;         // 0x0134(0x0014)(NoDestructor, HasGetValueTypeHash)
	TArray<int32>                                 K2Node_MakeArray_Array;                            // 0x0148(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Get_Item_1;                         // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x015D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15E[0x2];                                      // 0x015E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_4; // 0x0160(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_4;     // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_5; // 0x0178(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_5;     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_6; // 0x0190(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_6;     // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Anke_C_技能1按下) == 0x000008, "Wrong alignment on BP_Input_Anke_C_技能1按下");
static_assert(sizeof(BP_Input_Anke_C_技能1按下) == 0x0001A8, "Wrong size on BP_Input_Anke_C_技能1按下");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, time) == 0x000000, "Member 'BP_Input_Anke_C_技能1按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, ReturnValue) == 0x000004, "Member 'BP_Input_Anke_C_技能1按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc___1___ReturnValue) == 0x000018, "Member 'BP_Input_Anke_C_技能1按下::CallFunc___1___ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, ___int_Variable) == 0x00002C, "Member 'BP_Input_Anke_C_技能1按下::___int_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x000030, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x000044, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, ___bool_True_if_break_was_hit_Variable) == 0x000058, "Member 'BP_Input_Anke_C_技能1按下::___bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Not_PreBool_ReturnValue) == 0x000059, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue_2) == 0x00005C, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, ___int_Loop_Counter_Variable) == 0x000070, "Member 'BP_Input_Anke_C_技能1按下::___int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Add_IntInt_ReturnValue) == 0x000074, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000078, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000088, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000089, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x00008A, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00008B, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, ___int_Variable_1) == 0x00008C, "Member 'BP_Input_Anke_C_技能1按下::___int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_BooleanAND_ReturnValue) == 0x000090, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_BooleanOR_ReturnValue) == 0x000091, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, ___int_Array_Index_Variable) == 0x000094, "Member 'BP_Input_Anke_C_技能1按下::___int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput_1) == 0x000098, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue_1) == 0x0000A8, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x0000B0, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_BreakGameplayTagContainer_GameplayTags) == 0x0000D0, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_BreakGameplayTagContainer_GameplayTags' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Array_Get_Item) == 0x0000E0, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput_2) == 0x0000F0, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue_2) == 0x000100, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Array_Length_ReturnValue) == 0x000104, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Less_IntInt_ReturnValue) == 0x000108, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_BooleanAND_ReturnValue_1) == 0x000109, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue_3) == 0x00010C, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput_3) == 0x000120, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue_3) == 0x000130, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue_4) == 0x000134, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, K2Node_MakeArray_Array) == 0x000148, "Member 'BP_Input_Anke_C_技能1按下::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Array_Get_Item_1) == 0x000158, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_Array_IsValidIndex_ReturnValue) == 0x00015C, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_CanResponseInput_ReturnValue) == 0x00015D, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput_4) == 0x000160, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue_4) == 0x000170, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput_5) == 0x000178, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue_5) == 0x000188, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput_6) == 0x000190, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue_6) == 0x0001A0, "Member 'BP_Input_Anke_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue_6' has a wrong offset!");

// Function BP_Input_Anke.BP_Input_Anke_C.大招按下
// 0x0040 (0x0040 - 0x0000)
struct BP_Input_Anke_C_大招按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0020(0x0014)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue;     // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue_1;   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Anke_C_大招按下) == 0x000004, "Wrong alignment on BP_Input_Anke_C_大招按下");
static_assert(sizeof(BP_Input_Anke_C_大招按下) == 0x000040, "Wrong size on BP_Input_Anke_C_大招按下");
static_assert(offsetof(BP_Input_Anke_C_大招按下, time) == 0x000000, "Member 'BP_Input_Anke_C_大招按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, ReturnValue) == 0x000004, "Member 'BP_Input_Anke_C_大招按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_CanResponseInput_ReturnValue) == 0x000018, "Member 'BP_Input_Anke_C_大招按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000019, "Member 'BP_Input_Anke_C_大招按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x00001A, "Member 'BP_Input_Anke_C_大招按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00001B, "Member 'BP_Input_Anke_C_大招按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_BooleanAND_ReturnValue) == 0x00001C, "Member 'BP_Input_Anke_C_大招按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_BooleanOR_ReturnValue) == 0x00001D, "Member 'BP_Input_Anke_C_大招按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x000020, "Member 'BP_Input_Anke_C_大招按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_GetAttributeCurrentValue_ReturnValue) == 0x000034, "Member 'BP_Input_Anke_C_大招按下::CallFunc_GetAttributeCurrentValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_GetAttributeCurrentValue_ReturnValue_1) == 0x000038, "Member 'BP_Input_Anke_C_大招按下::CallFunc_GetAttributeCurrentValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招按下, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x00003C, "Member 'BP_Input_Anke_C_大招按下::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");

// Function BP_Input_Anke.BP_Input_Anke_C.大招长按
// 0x0018 (0x0018 - 0x0000)
struct BP_Input_Anke_C_大招长按 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Input_Anke_C_大招长按) == 0x000004, "Wrong alignment on BP_Input_Anke_C_大招长按");
static_assert(sizeof(BP_Input_Anke_C_大招长按) == 0x000018, "Wrong size on BP_Input_Anke_C_大招长按");
static_assert(offsetof(BP_Input_Anke_C_大招长按, time) == 0x000000, "Member 'BP_Input_Anke_C_大招长按::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Anke_C_大招长按, ReturnValue) == 0x000004, "Member 'BP_Input_Anke_C_大招长按::ReturnValue' has a wrong offset!");

}

