#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Input_Maxiaofang

#include "Basic.hpp"

#include "sInputCommand_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "ECharViewDirectionState_structs.hpp"


namespace SDK::Params
{

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.攻击按下
// 0x0178 (0x0178 - 0x0000)
struct BP_Input_Maxiaofang_C_攻击按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc______ReturnValue;                         // 0x0018(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x002C(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x0040(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_2;         // 0x0054(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_3;         // 0x006C(0x0014)(NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x0092(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0093(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0094(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0095(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_96[0x2];                                       // 0x0096(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_1; // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_1;     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_2; // 0x00B0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_2;     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_3; // 0x00C8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_3;     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECharViewDirectionState                       CallFunc_GetDirectionState_ReturnValue;            // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DA[0x2];                                       // 0x00DA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_4;         // 0x00DC(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_4; // 0x00F8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_4;     // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_5;         // 0x010C(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_6;         // 0x0120(0x0014)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_5; // 0x0138(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_5;     // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x3];                                      // 0x0149(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_7;         // 0x014C(0x0014)(NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_6; // 0x0160(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_6;     // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_攻击按下) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_攻击按下");
static_assert(sizeof(BP_Input_Maxiaofang_C_攻击按下) == 0x000178, "Wrong size on BP_Input_Maxiaofang_C_攻击按下");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_攻击按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_攻击按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc______ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc______ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x00002C, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x000040, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_2) == 0x000054, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CanResponseInput_ReturnValue) == 0x000068, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_3) == 0x00006C, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000080, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000090, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000091, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x000092, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000093, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_BooleanAND_ReturnValue) == 0x000094, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_BooleanOR_ReturnValue) == 0x000095, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_1) == 0x000098, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_1) == 0x0000A8, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_2) == 0x0000B0, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_2) == 0x0000C0, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_3) == 0x0000C8, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_3) == 0x0000D8, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_GetDirectionState_ReturnValue) == 0x0000D9, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_GetDirectionState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_4) == 0x0000DC, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x0000F0, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_4) == 0x0000F8, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_4) == 0x000108, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_5) == 0x00010C, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_6) == 0x000120, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_5) == 0x000138, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_5) == 0x000148, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_CreateSkillCommand_ReturnValue_7) == 0x00014C, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_CreateSkillCommand_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_self_CastInput_6) == 0x000160, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_self_CastInput_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击按下, CallFunc_HasMatchingGameplayTag_ReturnValue_6) == 0x000170, "Member 'BP_Input_Maxiaofang_C_攻击按下::CallFunc_HasMatchingGameplayTag_ReturnValue_6' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.攻击长按
// 0x0060 (0x0060 - 0x0000)
struct BP_Input_Maxiaofang_C_攻击长按 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc______ReturnValue;                         // 0x0018(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECharViewDirectionState                       CallFunc_GetDirectionState_ReturnValue;            // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x002F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0030(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0047(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0048(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_攻击长按) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_攻击长按");
static_assert(sizeof(BP_Input_Maxiaofang_C_攻击长按) == 0x000060, "Wrong size on BP_Input_Maxiaofang_C_攻击长按");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_攻击长按::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_攻击长按::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc______ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc______ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_CanResponseInput_ReturnValue) == 0x00002C, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_GetDirectionState_ReturnValue) == 0x00002D, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_GetDirectionState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00002E, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00002F, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_CreateSkillCommand_ReturnValue) == 0x000030, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000044, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_IsMovingOnGround_ReturnValue) == 0x000045, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_BooleanAND_ReturnValue) == 0x000046, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_BooleanOR_ReturnValue) == 0x000047, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000048, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击长按, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000058, "Member 'BP_Input_Maxiaofang_C_攻击长按::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.攻击抬起
// 0x0220 (0x0220 - 0x0000)
struct BP_Input_Maxiaofang_C_攻击抬起 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc______ReturnValue;                         // 0x0018(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue; // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0030(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x0044(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_True_if_break_was_hit_Variable;            // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Variable;                                   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_2;         // 0x0060(0x0014)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x0078(0x0020)()
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_3;         // 0x0098(0x0014)(NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Array_Index_Variable;                       // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECharViewDirectionState                       CallFunc_GetDirectionState_ReturnValue;            // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetSkillAcceptInput_ReturnValue;          // 0x00B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B5[0x3];                                       // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_4;         // 0x00B8(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x00CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00CE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00CF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         ___int_Variable_1;                                 // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x00D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_1; // 0x00F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_1;     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x3];                                      // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_5;         // 0x0104(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_6;         // 0x0118(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_7;         // 0x012C(0x0014)(NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_2; // 0x0140(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_2;     // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue_1; // 0x0158(0x0020)()
	TArray<struct FGameplayTag>                   CallFunc_BreakGameplayTagContainer_GameplayTags;   // 0x0178(0x0010)(ReferenceParm)
	struct FGameplayTag                           CallFunc_Array_Get_Item;                           // 0x0188(0x000C)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_3; // 0x0198(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_3;     // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 K2Node_MakeArray_Array;                            // 0x01B0(0x0010)(ReferenceParm)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_4; // 0x01C0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_4;     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x3];                                      // 0x01D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Get_Item_1;                         // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D9[0x3];                                      // 0x01D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Loop_Counter_Variable;                      // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E1[0x3];                                      // 0x01E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_5; // 0x01F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_5;     // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasAnyMatchingGameplayTags_self_CastInput; // 0x0208(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAnyMatchingGameplayTags_ReturnValue;   // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0219(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_攻击抬起) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_攻击抬起");
static_assert(sizeof(BP_Input_Maxiaofang_C_攻击抬起) == 0x000220, "Wrong size on BP_Input_Maxiaofang_C_攻击抬起");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_攻击抬起::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_攻击抬起::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc______ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc______ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue) == 0x00002C, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_GetCommonSkillCanBeInterrupt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue) == 0x000030, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x000044, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, ___bool_True_if_break_was_hit_Variable) == 0x000058, "Member 'BP_Input_Maxiaofang_C_攻击抬起::___bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Not_PreBool_ReturnValue) == 0x000059, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, ___int_Variable) == 0x00005C, "Member 'BP_Input_Maxiaofang_C_攻击抬起::___int_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_2) == 0x000060, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x000078, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_3) == 0x000098, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, ___int_Array_Index_Variable) == 0x0000AC, "Member 'BP_Input_Maxiaofang_C_攻击抬起::___int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CanResponseInput_ReturnValue) == 0x0000B0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_GetDirectionState_ReturnValue) == 0x0000B1, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_GetDirectionState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000B2, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_GetSkillAcceptInput_ReturnValue) == 0x0000B3, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_GetSkillAcceptInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0000B4, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_4) == 0x0000B8, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x0000CC, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_IsMovingOnGround_ReturnValue) == 0x0000CD, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_BooleanAND_ReturnValue) == 0x0000CE, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_BooleanOR_ReturnValue) == 0x0000CF, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, ___int_Variable_1) == 0x0000D0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::___int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x0000D8, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x0000E8, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_self_CastInput_1) == 0x0000F0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_self_CastInput_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_ReturnValue_1) == 0x000100, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_5) == 0x000104, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_6) == 0x000118, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_CreateSkillCommand_ReturnValue_7) == 0x00012C, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_CreateSkillCommand_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_self_CastInput_2) == 0x000140, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_self_CastInput_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_ReturnValue_2) == 0x000150, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue_1) == 0x000158, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_BreakGameplayTagContainer_GameplayTags) == 0x000178, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_BreakGameplayTagContainer_GameplayTags' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Array_Get_Item) == 0x000188, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Array_Length_ReturnValue) == 0x000194, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_self_CastInput_3) == 0x000198, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_self_CastInput_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_ReturnValue_3) == 0x0001A8, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, K2Node_MakeArray_Array) == 0x0001B0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_self_CastInput_4) == 0x0001C0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_self_CastInput_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_ReturnValue_4) == 0x0001D0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Array_Get_Item_1) == 0x0001D4, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Array_IsValidIndex_ReturnValue) == 0x0001D8, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, ___int_Loop_Counter_Variable) == 0x0001DC, "Member 'BP_Input_Maxiaofang_C_攻击抬起::___int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Less_IntInt_ReturnValue) == 0x0001E0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Add_IntInt_ReturnValue) == 0x0001E4, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_BooleanAND_ReturnValue_1) == 0x0001E8, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_self_CastInput_5) == 0x0001F0, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_self_CastInput_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasMatchingGameplayTag_ReturnValue_5) == 0x000200, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasMatchingGameplayTag_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasAnyMatchingGameplayTags_self_CastInput) == 0x000208, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasAnyMatchingGameplayTags_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_HasAnyMatchingGameplayTags_ReturnValue) == 0x000218, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_HasAnyMatchingGameplayTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_攻击抬起, CallFunc_Not_PreBool_ReturnValue_1) == 0x000219, "Member 'BP_Input_Maxiaofang_C_攻击抬起::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.大招按下
// 0x0044 (0x0044 - 0x0000)
struct BP_Input_Maxiaofang_C_大招按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x001C(0x0014)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue;     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0037(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue_1;   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_大招按下) == 0x000004, "Wrong alignment on BP_Input_Maxiaofang_C_大招按下");
static_assert(sizeof(BP_Input_Maxiaofang_C_大招按下) == 0x000044, "Wrong size on BP_Input_Maxiaofang_C_大招按下");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_大招按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_大招按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_CanResponseInput_ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x00001C, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_GetAttributeCurrentValue_ReturnValue) == 0x000030, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_GetAttributeCurrentValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000034, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x000035, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000036, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_BooleanAND_ReturnValue) == 0x000037, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_BooleanOR_ReturnValue) == 0x000038, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_GetAttributeCurrentValue_ReturnValue_1) == 0x00003C, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_GetAttributeCurrentValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_大招按下, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000040, "Member 'BP_Input_Maxiaofang_C_大招按下::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.幻象1按下
// 0x0050 (0x0050 - 0x0000)
struct BP_Input_Maxiaofang_C_幻象1按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc___1___ReturnValue;                        // 0x0018(0x0014)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Maxiaofang_C*                       K2Node_DynamicCast_AsBP_Maxiaofang;                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x003C(0x0014)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Input_Maxiaofang_C_幻象1按下) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_幻象1按下");
static_assert(sizeof(BP_Input_Maxiaofang_C_幻象1按下) == 0x000050, "Wrong size on BP_Input_Maxiaofang_C_幻象1按下");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象1按下, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_幻象1按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象1按下, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_幻象1按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象1按下, CallFunc___1___ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_幻象1按下::CallFunc___1___ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象1按下, K2Node_DynamicCast_AsBP_Maxiaofang) == 0x000030, "Member 'BP_Input_Maxiaofang_C_幻象1按下::K2Node_DynamicCast_AsBP_Maxiaofang' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象1按下, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BP_Input_Maxiaofang_C_幻象1按下::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象1按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x00003C, "Member 'BP_Input_Maxiaofang_C_幻象1按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.幻象2按下
// 0x0050 (0x0050 - 0x0000)
struct BP_Input_Maxiaofang_C_幻象2按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	class ABP_Maxiaofang_C*                       K2Node_DynamicCast_AsBP_Maxiaofang;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x0024(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc___2___ReturnValue;                        // 0x0038(0x0014)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Input_Maxiaofang_C_幻象2按下) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_幻象2按下");
static_assert(sizeof(BP_Input_Maxiaofang_C_幻象2按下) == 0x000050, "Wrong size on BP_Input_Maxiaofang_C_幻象2按下");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象2按下, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_幻象2按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象2按下, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_幻象2按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象2按下, K2Node_DynamicCast_AsBP_Maxiaofang) == 0x000018, "Member 'BP_Input_Maxiaofang_C_幻象2按下::K2Node_DynamicCast_AsBP_Maxiaofang' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象2按下, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_Input_Maxiaofang_C_幻象2按下::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象2按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x000024, "Member 'BP_Input_Maxiaofang_C_幻象2按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_幻象2按下, CallFunc___2___ReturnValue) == 0x000038, "Member 'BP_Input_Maxiaofang_C_幻象2按下::CallFunc___2___ReturnValue' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.瞄准按下
// 0x00A8 (0x00A8 - 0x0000)
struct BP_Input_Maxiaofang_C_瞄准按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x0018(0x0020)()
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasAnyMatchingGameplayTags_self_CastInput; // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAnyMatchingGameplayTags_ReturnValue;   // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A[0x2];                                       // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x004C(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc______ReturnValue;                         // 0x0060(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x0074(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECharViewDirectionState                       CallFunc_GetDirectionState_ReturnValue;            // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x008A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x008B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x008D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x008E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x008F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0090(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_瞄准按下) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_瞄准按下");
static_assert(sizeof(BP_Input_Maxiaofang_C_瞄准按下) == 0x0000A8, "Wrong size on BP_Input_Maxiaofang_C_瞄准按下");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_瞄准按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_瞄准按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_HasAnyMatchingGameplayTags_self_CastInput) == 0x000038, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_HasAnyMatchingGameplayTags_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_HasAnyMatchingGameplayTags_ReturnValue) == 0x000048, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_HasAnyMatchingGameplayTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_Not_PreBool_ReturnValue) == 0x000049, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x00004C, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc______ReturnValue) == 0x000060, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc______ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x000074, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_CanResponseInput_ReturnValue) == 0x000088, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_GetDirectionState_ReturnValue) == 0x000089, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_GetDirectionState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00008A, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00008B, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x00008C, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x00008D, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_BooleanAND_ReturnValue) == 0x00008E, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_BooleanOR_ReturnValue) == 0x00008F, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000090, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准按下, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x0000A0, "Member 'BP_Input_Maxiaofang_C_瞄准按下::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.技能1按下
// 0x00B0 (0x00B0 - 0x0000)
struct BP_Input_Maxiaofang_C_技能1按下 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  CallFunc_MakeLiteralGameplayTagContainer_ReturnValue; // 0x0018(0x0020)()
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasAnyMatchingGameplayTags_self_CastInput; // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAnyMatchingGameplayTags_ReturnValue;   // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A[0x2];                                       // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x004C(0x0014)(NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc___1___ReturnValue;                        // 0x0060(0x0014)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAttributeCurrentValue_ReturnValue;     // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x007E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x007F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue_1;         // 0x0080(0x0014)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_技能1按下) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_技能1按下");
static_assert(sizeof(BP_Input_Maxiaofang_C_技能1按下) == 0x0000B0, "Wrong size on BP_Input_Maxiaofang_C_技能1按下");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_技能1按下::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_技能1按下::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_MakeLiteralGameplayTagContainer_ReturnValue) == 0x000018, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_MakeLiteralGameplayTagContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_HasAnyMatchingGameplayTags_self_CastInput) == 0x000038, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_HasAnyMatchingGameplayTags_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_HasAnyMatchingGameplayTags_ReturnValue) == 0x000048, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_HasAnyMatchingGameplayTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_Not_PreBool_ReturnValue) == 0x000049, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue) == 0x00004C, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc___1___ReturnValue) == 0x000060, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc___1___ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_GetAttributeCurrentValue_ReturnValue) == 0x000074, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_GetAttributeCurrentValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000078, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000079, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_BooleanAND_ReturnValue) == 0x00007A, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00007B, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_BooleanAND_ReturnValue_1) == 0x00007C, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_IsMovingOnGround_ReturnValue) == 0x00007D, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_BooleanOR_ReturnValue) == 0x00007E, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_CanResponseInput_ReturnValue) == 0x00007F, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_CreateSkillCommand_ReturnValue_1) == 0x000080, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_CreateSkillCommand_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000098, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1按下, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x0000A8, "Member 'BP_Input_Maxiaofang_C_技能1按下::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.技能1抬起
// 0x0068 (0x0068 - 0x0000)
struct BP_Input_Maxiaofang_C_技能1抬起 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	float                                         长按时长;                                          // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         CallFunc_CreateSkillCommand_ReturnValue;           // 0x001C(0x0014)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanResponseInput_ReturnValue;             // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMovingOnGround_ReturnValue;             // 0x0033(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_37[0x1];                                       // 0x0037(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput_1; // 0x0050(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue_1;     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Input_Maxiaofang_C_技能1抬起) == 0x000008, "Wrong alignment on BP_Input_Maxiaofang_C_技能1抬起");
static_assert(sizeof(BP_Input_Maxiaofang_C_技能1抬起) == 0x000068, "Wrong size on BP_Input_Maxiaofang_C_技能1抬起");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_技能1抬起::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_技能1抬起::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, 长按时长) == 0x000018, "Member 'BP_Input_Maxiaofang_C_技能1抬起::长按时长' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_CreateSkillCommand_ReturnValue) == 0x00001C, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_CreateSkillCommand_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_CanResponseInput_ReturnValue) == 0x000030, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_CanResponseInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000031, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000032, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_IsMovingOnGround_ReturnValue) == 0x000033, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_IsMovingOnGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000034, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_BooleanAND_ReturnValue) == 0x000035, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_BooleanOR_ReturnValue) == 0x000036, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000038, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000048, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_HasMatchingGameplayTag_self_CastInput_1) == 0x000050, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_HasMatchingGameplayTag_self_CastInput_1' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_技能1抬起, CallFunc_HasMatchingGameplayTag_ReturnValue_1) == 0x000060, "Member 'BP_Input_Maxiaofang_C_技能1抬起::CallFunc_HasMatchingGameplayTag_ReturnValue_1' has a wrong offset!");

// Function BP_Input_Maxiaofang.BP_Input_Maxiaofang_C.瞄准抬起
// 0x0018 (0x0018 - 0x0000)
struct BP_Input_Maxiaofang_C_瞄准抬起 final
{
public:
	float                                         time;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSInputCommand                         ReturnValue;                                       // 0x0004(0x0014)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Input_Maxiaofang_C_瞄准抬起) == 0x000004, "Wrong alignment on BP_Input_Maxiaofang_C_瞄准抬起");
static_assert(sizeof(BP_Input_Maxiaofang_C_瞄准抬起) == 0x000018, "Wrong size on BP_Input_Maxiaofang_C_瞄准抬起");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准抬起, time) == 0x000000, "Member 'BP_Input_Maxiaofang_C_瞄准抬起::time' has a wrong offset!");
static_assert(offsetof(BP_Input_Maxiaofang_C_瞄准抬起, ReturnValue) == 0x000004, "Member 'BP_Input_Maxiaofang_C_瞄准抬起::ReturnValue' has a wrong offset!");

}

