#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Yangyang

#include "Basic.hpp"

#include "BP_Yangyang_classes.hpp"
#include "BP_Yangyang_parameters.hpp"


namespace SDK
{

// Function BP_Yangyang.BP_Yangyang_C.FightCommand
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isInAir                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Yangyang_C::FightCommand(bool isInAir)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yangyang_C", "FightCommand");

	Params::BP_Yangyang_C_FightCommand Parms{};

	Parms.isInAir = isInAir;

	UObject::ProcessEvent(Func, &Parms);
}

}

