#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_XiaofangBurst_2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_XiaofangBurst_2.CS_XiaofangBurst_2_C
// 0x0000 (0x01A0 - 0x01A0)
class UCS_XiaofangBurst_2_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CS_XiaofangBurst_2_C">();
	}
	static class UCS_XiaofangBurst_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_XiaofangBurst_2_C>();
	}
};
static_assert(alignof(UCS_XiaofangBurst_2_C) == 0x000010, "Wrong alignment on UCS_XiaofangBurst_2_C");
static_assert(sizeof(UCS_XiaofangBurst_2_C) == 0x0001A0, "Wrong size on UCS_XiaofangBurst_2_C");

}

