#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Maxiaofang_Attack04

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Maxiaofang_Attack04.GA_Maxiaofang_Attack04_C
// 0x0010 (0x0568 - 0x0558)
class UGA_Maxiaofang_Attack04_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Maxiaofang_Attack04_C;           // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         累计时间;                                          // 0x0560(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Maxiaofang_Attack04(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void OnCompleted_5D118C384AE61F1C80292E8130709FDC();
	void OnBlendOut_5D118C384AE61F1C80292E8130709FDC();
	void OnInterrupted_5D118C384AE61F1C80292E8130709FDC();
	void OnCancelled_5D118C384AE61F1C80292E8130709FDC();
	void OnTick_5D118C384AE61F1C80292E8130709FDC();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Maxiaofang_Attack04_C">();
	}
	static class UGA_Maxiaofang_Attack04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Maxiaofang_Attack04_C>();
	}
};
static_assert(alignof(UGA_Maxiaofang_Attack04_C) == 0x000008, "Wrong alignment on UGA_Maxiaofang_Attack04_C");
static_assert(sizeof(UGA_Maxiaofang_Attack04_C) == 0x000568, "Wrong size on UGA_Maxiaofang_Attack04_C");
static_assert(offsetof(UGA_Maxiaofang_Attack04_C, UberGraphFrame_GA_Maxiaofang_Attack04_C) == 0x000558, "Member 'UGA_Maxiaofang_Attack04_C::UberGraphFrame_GA_Maxiaofang_Attack04_C' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_Attack04_C, 累计时间) == 0x000560, "Member 'UGA_Maxiaofang_Attack04_C::累计时间' has a wrong offset!");

}

