#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Maxiaofang_AimMode

#include "Basic.hpp"

#include "GA_Maxiaofang_AimMode_classes.hpp"
#include "GA_Maxiaofang_AimMode_parameters.hpp"


namespace SDK
{

// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.ExecuteUbergraph_GA_Maxiaofang_AimMode
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::ExecuteUbergraph_GA_Maxiaofang_AimMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "ExecuteUbergraph_GA_Maxiaofang_AimMode");

	Params::GA_Maxiaofang_AimMode_C_ExecuteUbergraph_GA_Maxiaofang_AimMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Maxiaofang_AimMode_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Maxiaofang_AimMode_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "K2_OnEndAbility");

	Params::GA_Maxiaofang_AimMode_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.Added_88C3E2B443F79876F7C23AB9CB8D383C
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::Added_88C3E2B443F79876F7C23AB9CB8D383C(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "Added_88C3E2B443F79876F7C23AB9CB8D383C");

	Params::GA_Maxiaofang_AimMode_C_Added_88C3E2B443F79876F7C23AB9CB8D383C Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.Added_F537773A455B59710A5696AE93D16B0A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::Added_F537773A455B59710A5696AE93D16B0A(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "Added_F537773A455B59710A5696AE93D16B0A");

	Params::GA_Maxiaofang_AimMode_C_Added_F537773A455B59710A5696AE93D16B0A Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.Added_F44D0FF24D8A3E9C548575AD2860BE06
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::Added_F44D0FF24D8A3E9C548575AD2860BE06(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "Added_F44D0FF24D8A3E9C548575AD2860BE06");

	Params::GA_Maxiaofang_AimMode_C_Added_F44D0FF24D8A3E9C548575AD2860BE06 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.Added_554AE36A49BA6253F1D88B8037F1EAB1
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::Added_554AE36A49BA6253F1D88B8037F1EAB1(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "Added_554AE36A49BA6253F1D88B8037F1EAB1");

	Params::GA_Maxiaofang_AimMode_C_Added_554AE36A49BA6253F1D88B8037F1EAB1 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.Added_DCA302F143C20C7BD8C1609ABE82E21D
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::Added_DCA302F143C20C7BD8C1609ABE82E21D(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "Added_DCA302F143C20C7BD8C1609ABE82E21D");

	Params::GA_Maxiaofang_AimMode_C_Added_DCA302F143C20C7BD8C1609ABE82E21D Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.Added_00B489BE45602D75A95BADA55A7017D7
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_C::Added_00B489BE45602D75A95BADA55A7017D7(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "Added_00B489BE45602D75A95BADA55A7017D7");

	Params::GA_Maxiaofang_AimMode_C_Added_00B489BE45602D75A95BADA55A7017D7 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.EventReceived_18B59F5945020DB23C42FD88F858F106
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_C::EventReceived_18B59F5945020DB23C42FD88F858F106(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "EventReceived_18B59F5945020DB23C42FD88F858F106");

	Params::GA_Maxiaofang_AimMode_C_EventReceived_18B59F5945020DB23C42FD88F858F106 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.OnFinish_34738D6943EB16CA33E2FA8523E42A0C
// (BlueprintCallable, BlueprintEvent)

void UGA_Maxiaofang_AimMode_C::OnFinish_34738D6943EB16CA33E2FA8523E42A0C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "OnFinish_34738D6943EB16CA33E2FA8523E42A0C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.EventReceived_18B59F5945020DB23C42FD88D839CFE6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_C::EventReceived_18B59F5945020DB23C42FD88D839CFE6(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "EventReceived_18B59F5945020DB23C42FD88D839CFE6");

	Params::GA_Maxiaofang_AimMode_C_EventReceived_18B59F5945020DB23C42FD88D839CFE6 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode.GA_Maxiaofang_AimMode_C.EventReceived_18B59F5945020DB23C42FD8821A91FD8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_C::EventReceived_18B59F5945020DB23C42FD8821A91FD8(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_C", "EventReceived_18B59F5945020DB23C42FD8821A91FD8");

	Params::GA_Maxiaofang_AimMode_C_EventReceived_18B59F5945020DB23C42FD8821A91FD8 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}

}

