#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Maxiaofang_Burst

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_Maxiaofang_Burst.GA_Maxiaofang_Burst_C.ExecuteUbergraph_GA_Maxiaofang_Burst
// 0x01B0 (0x01B0 - 0x0000)
struct GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc__________;                                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc______________;                            // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________1;                              // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________2;                              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________1;                          // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character;            // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0058(0x0028)(ZeroConstructor)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc___________3;                              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00A0(0x0028)(ZeroConstructor)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x00D8(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_____GA______________;                     // 0x0100(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0110(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________4;                              // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0158(0x0028)(ZeroConstructor)
	float                                         CallFunc__________SpeedRatio;                      // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Variable;                                   // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue; // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________5;                              // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_____Tag_____;                             // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x01AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x01AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst) == 0x000008, "Wrong alignment on GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst");
static_assert(sizeof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst) == 0x0001B0, "Wrong size on GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, EntryPoint) == 0x000000, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_Conv_IntToString_ReturnValue) == 0x000008, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc__________) == 0x000018, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc__________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc______________) == 0x000020, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc______________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc___________1) == 0x000028, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc___________1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc___________2) == 0x000030, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc___________2' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_______________1) == 0x000038, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_______________1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_GetOwningActorFromActorInfo_ReturnValue) == 0x000040, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_GetOwningActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_DynamicCast_AsTs_Base_Character) == 0x000048, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_DynamicCast_AsTs_Base_Character' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_CreateDelegate_OutputDelegate) == 0x000058, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000080, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc___________3) == 0x000088, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc___________3' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_GetDisplayName_ReturnValue) == 0x000090, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000A0, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_GetObjectClass_ReturnValue) == 0x0000C8, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x0000D0, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000D8, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_____GA______________) == 0x000100, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_____GA______________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_CreateDelegate_OutputDelegate_3) == 0x000110, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_Conv_NameToString_ReturnValue) == 0x000138, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc___________4) == 0x000148, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc___________4' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_IsValid_ReturnValue) == 0x000150, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_CreateDelegate_OutputDelegate_4) == 0x000158, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc__________SpeedRatio) == 0x000180, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc__________SpeedRatio' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, ___int_Variable) == 0x000184, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::___int_Variable' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue) == 0x000188, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_IsValid_ReturnValue_1) == 0x000190, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_Add_IntInt_ReturnValue) == 0x000194, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, K2Node_Event_bWasCancelled) == 0x000198, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc___________5) == 0x0001A0, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc___________5' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_____Tag_____) == 0x0001A8, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_____Tag_____' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_LessEqual_IntInt_ReturnValue) == 0x0001AC, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst, CallFunc_Greater_IntInt_ReturnValue) == 0x0001AD, "Member 'GA_Maxiaofang_Burst_C_ExecuteUbergraph_GA_Maxiaofang_Burst::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function GA_Maxiaofang_Burst.GA_Maxiaofang_Burst_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_Maxiaofang_Burst_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Maxiaofang_Burst_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_Maxiaofang_Burst_C_K2_OnEndAbility");
static_assert(sizeof(GA_Maxiaofang_Burst_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_Maxiaofang_Burst_C_K2_OnEndAbility");
static_assert(offsetof(GA_Maxiaofang_Burst_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_Maxiaofang_Burst_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

