#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Maxiaofang_AimMode_Loop

#include "Basic.hpp"

#include "GA_Maxiaofang_AimMode_Loop_classes.hpp"
#include "GA_Maxiaofang_AimMode_Loop_parameters.hpp"


namespace SDK
{

// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.ExecuteUbergraph_GA_Maxiaofang_AimMode_Loop
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::ExecuteUbergraph_GA_Maxiaofang_AimMode_Loop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "ExecuteUbergraph_GA_Maxiaofang_AimMode_Loop");

	Params::GA_Maxiaofang_AimMode_Loop_C_ExecuteUbergraph_GA_Maxiaofang_AimMode_Loop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Maxiaofang_AimMode_Loop_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "K2_OnEndAbility");

	Params::GA_Maxiaofang_AimMode_Loop_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Maxiaofang_AimMode_Loop_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.Added_129D674C49914853E61BAA843756B3A7
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::Added_129D674C49914853E61BAA843756B3A7(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "Added_129D674C49914853E61BAA843756B3A7");

	Params::GA_Maxiaofang_AimMode_Loop_C_Added_129D674C49914853E61BAA843756B3A7 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.Added_02D99AA140CC5B92CED34782987D0684
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::Added_02D99AA140CC5B92CED34782987D0684(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "Added_02D99AA140CC5B92CED34782987D0684");

	Params::GA_Maxiaofang_AimMode_Loop_C_Added_02D99AA140CC5B92CED34782987D0684 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.Added_BC67FB574DEA8972B6691AA7364E8454
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::Added_BC67FB574DEA8972B6691AA7364E8454(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "Added_BC67FB574DEA8972B6691AA7364E8454");

	Params::GA_Maxiaofang_AimMode_Loop_C_Added_BC67FB574DEA8972B6691AA7364E8454 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.Removed_48C7D5FA45CC3B71CAF968B787541A28
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::Removed_48C7D5FA45CC3B71CAF968B787541A28(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "Removed_48C7D5FA45CC3B71CAF968B787541A28");

	Params::GA_Maxiaofang_AimMode_Loop_C_Removed_48C7D5FA45CC3B71CAF968B787541A28 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.Added_3DEAF8604C601E6160B0D49E737EA696
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::Added_3DEAF8604C601E6160B0D49E737EA696(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "Added_3DEAF8604C601E6160B0D49E737EA696");

	Params::GA_Maxiaofang_AimMode_Loop_C_Added_3DEAF8604C601E6160B0D49E737EA696 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.Added_9EF720FF469274BDB874BCABD0DDAAE6
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Maxiaofang_AimMode_Loop_C::Added_9EF720FF469274BDB874BCABD0DDAAE6(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "Added_9EF720FF469274BDB874BCABD0DDAAE6");

	Params::GA_Maxiaofang_AimMode_Loop_C_Added_9EF720FF469274BDB874BCABD0DDAAE6 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.EventReceived_18B59F5945020DB23C42FD880BCDD645
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_Loop_C::EventReceived_18B59F5945020DB23C42FD880BCDD645(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "EventReceived_18B59F5945020DB23C42FD880BCDD645");

	Params::GA_Maxiaofang_AimMode_Loop_C_EventReceived_18B59F5945020DB23C42FD880BCDD645 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.EventReceived_18B59F5945020DB23C42FD88B1481C46
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_Loop_C::EventReceived_18B59F5945020DB23C42FD88B1481C46(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "EventReceived_18B59F5945020DB23C42FD88B1481C46");

	Params::GA_Maxiaofang_AimMode_Loop_C_EventReceived_18B59F5945020DB23C42FD88B1481C46 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.EventReceived_18B59F5945020DB23C42FD8863BF4F7D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_Loop_C::EventReceived_18B59F5945020DB23C42FD8863BF4F7D(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "EventReceived_18B59F5945020DB23C42FD8863BF4F7D");

	Params::GA_Maxiaofang_AimMode_Loop_C_EventReceived_18B59F5945020DB23C42FD8863BF4F7D Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Maxiaofang_AimMode_Loop.GA_Maxiaofang_AimMode_Loop_C.EventReceived_18B59F5945020DB23C42FD884A1ECF7F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Maxiaofang_AimMode_Loop_C::EventReceived_18B59F5945020DB23C42FD884A1ECF7F(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Maxiaofang_AimMode_Loop_C", "EventReceived_18B59F5945020DB23C42FD884A1ECF7F");

	Params::GA_Maxiaofang_AimMode_Loop_C_EventReceived_18B59F5945020DB23C42FD884A1ECF7F Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}

}

