#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Maxiaofang_HoldShot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SCameraModifier_Condition_structs.hpp"
#include "EMovementDirection_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SCameraModifier_Settings_structs.hpp"
#include "ECharViewDirectionState_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Maxiaofang_HoldShot.GA_Maxiaofang_HoldShot_C
// 0x03A8 (0x0900 - 0x0558)
class UGA_Maxiaofang_HoldShot_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Maxiaofang_HoldShot_C;           // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UGameplayTask_WaitDelay*                Async_Task;                                        // 0x0560(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               目标面向;                                          // 0x0568(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FVector                                移动输入;                                          // 0x0574(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         镜头Yaw偏移;                                       // 0x0580(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         镜头Pitch偏移;                                     // 0x0584(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSCameraModifier_Settings              镜头参数配置_锁定偏移;                             // 0x0588(0x0118)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FSCameraModifier_Settings              镜头参数还原;                                      // 0x06A0(0x0118)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FSCameraModifier_Settings              镜头参数配置_非锁定;                               // 0x07B8(0x0118)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         丢失目标时间;                                      // 0x08D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         丢失目标最大时间;                                  // 0x08D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         目标视野外计时;                                    // 0x08D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         触发镜头回正时间;                                  // 0x08DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               上一帧镜头旋转;                                    // 0x08E0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          镜头回正中;                                        // 0x08EC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          注视镜头Modify;                                    // 0x08ED(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8EE[0x2];                                      // 0x08EE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSCameraModifier_Condition>     Camera_Modifier_Contions;                          // 0x08F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_Maxiaofang_HoldShot(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void OnTick_8D96293640861CE3D30811B2970CE1FD();
	void OnFinish_8D96293640861CE3D30811B2970CE1FD();
	void OnTick_8D96293640861CE3D30811B289F52F19();
	void OnFinish_8D96293640861CE3D30811B289F52F19();
	void OnCompleted_5D118C384AE61F1C80292E812F14A6C8();
	void OnBlendOut_5D118C384AE61F1C80292E812F14A6C8();
	void OnInterrupted_5D118C384AE61F1C80292E812F14A6C8();
	void OnCancelled_5D118C384AE61F1C80292E812F14A6C8();
	void OnTick_5D118C384AE61F1C80292E812F14A6C8();
	void OnCompleted_5D118C384AE61F1C80292E81225AC48A();
	void OnBlendOut_5D118C384AE61F1C80292E81225AC48A();
	void OnInterrupted_5D118C384AE61F1C80292E81225AC48A();
	void OnCancelled_5D118C384AE61F1C80292E81225AC48A();
	void OnTick_5D118C384AE61F1C80292E81225AC48A();
	void OnCompleted_5D118C384AE61F1C80292E81BFCBA22C();
	void OnBlendOut_5D118C384AE61F1C80292E81BFCBA22C();
	void OnInterrupted_5D118C384AE61F1C80292E81BFCBA22C();
	void OnCancelled_5D118C384AE61F1C80292E81BFCBA22C();
	void OnTick_5D118C384AE61F1C80292E81BFCBA22C();
	void Added_21071CB943CD992BF8EFD6A341D4E06E(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A33D1E8C2A(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A3EA7B0AD3(const struct FGameplayTag& Tag);
	void OnCompleted_5D118C384AE61F1C80292E815F1F659C();
	void OnBlendOut_5D118C384AE61F1C80292E815F1F659C();
	void OnInterrupted_5D118C384AE61F1C80292E815F1F659C();
	void OnCancelled_5D118C384AE61F1C80292E815F1F659C();
	void OnTick_5D118C384AE61F1C80292E815F1F659C();
	void OnCompleted_5D118C384AE61F1C80292E81C7FD42B0();
	void OnBlendOut_5D118C384AE61F1C80292E81C7FD42B0();
	void OnInterrupted_5D118C384AE61F1C80292E81C7FD42B0();
	void OnCancelled_5D118C384AE61F1C80292E81C7FD42B0();
	void OnTick_5D118C384AE61F1C80292E81C7FD42B0();
	void OnCompleted_5D118C384AE61F1C80292E813F0DF815();
	void OnBlendOut_5D118C384AE61F1C80292E813F0DF815();
	void OnInterrupted_5D118C384AE61F1C80292E813F0DF815();
	void OnCancelled_5D118C384AE61F1C80292E813F0DF815();
	void OnTick_5D118C384AE61F1C80292E813F0DF815();
	void 平滑角度计算_按时间_线性(float 角度1, float 角度2, float 剩余时间, float* 本帧角度);
	void 计算目标pitch(float* 目标角度);
	void 计算技能方向(float 角度, float 左前界限, float 右前界限, float 左后界限, float 右后界限, bool 是否有移动输入, EMovementDirection* 技能方向);
	void 平滑角度计算_按速度_非线性(float 角度1, float 角度2, float 插值速度, float* 本帧角度);
	void 平滑角度计算_按速度_线性(float 角度1, float 角度2, float 平滑速度, float* 本帧角度);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Maxiaofang_HoldShot_C">();
	}
	static class UGA_Maxiaofang_HoldShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Maxiaofang_HoldShot_C>();
	}
};
static_assert(alignof(UGA_Maxiaofang_HoldShot_C) == 0x000008, "Wrong alignment on UGA_Maxiaofang_HoldShot_C");
static_assert(sizeof(UGA_Maxiaofang_HoldShot_C) == 0x000900, "Wrong size on UGA_Maxiaofang_HoldShot_C");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, UberGraphFrame_GA_Maxiaofang_HoldShot_C) == 0x000558, "Member 'UGA_Maxiaofang_HoldShot_C::UberGraphFrame_GA_Maxiaofang_HoldShot_C' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, Async_Task) == 0x000560, "Member 'UGA_Maxiaofang_HoldShot_C::Async_Task' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 目标面向) == 0x000568, "Member 'UGA_Maxiaofang_HoldShot_C::目标面向' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 移动输入) == 0x000574, "Member 'UGA_Maxiaofang_HoldShot_C::移动输入' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 镜头Yaw偏移) == 0x000580, "Member 'UGA_Maxiaofang_HoldShot_C::镜头Yaw偏移' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 镜头Pitch偏移) == 0x000584, "Member 'UGA_Maxiaofang_HoldShot_C::镜头Pitch偏移' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 镜头参数配置_锁定偏移) == 0x000588, "Member 'UGA_Maxiaofang_HoldShot_C::镜头参数配置_锁定偏移' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 镜头参数还原) == 0x0006A0, "Member 'UGA_Maxiaofang_HoldShot_C::镜头参数还原' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 镜头参数配置_非锁定) == 0x0007B8, "Member 'UGA_Maxiaofang_HoldShot_C::镜头参数配置_非锁定' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 丢失目标时间) == 0x0008D0, "Member 'UGA_Maxiaofang_HoldShot_C::丢失目标时间' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 丢失目标最大时间) == 0x0008D4, "Member 'UGA_Maxiaofang_HoldShot_C::丢失目标最大时间' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 目标视野外计时) == 0x0008D8, "Member 'UGA_Maxiaofang_HoldShot_C::目标视野外计时' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 触发镜头回正时间) == 0x0008DC, "Member 'UGA_Maxiaofang_HoldShot_C::触发镜头回正时间' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 上一帧镜头旋转) == 0x0008E0, "Member 'UGA_Maxiaofang_HoldShot_C::上一帧镜头旋转' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 镜头回正中) == 0x0008EC, "Member 'UGA_Maxiaofang_HoldShot_C::镜头回正中' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, 注视镜头Modify) == 0x0008ED, "Member 'UGA_Maxiaofang_HoldShot_C::注视镜头Modify' has a wrong offset!");
static_assert(offsetof(UGA_Maxiaofang_HoldShot_C, Camera_Modifier_Contions) == 0x0008F0, "Member 'UGA_Maxiaofang_HoldShot_C::Camera_Modifier_Contions' has a wrong offset!");

}

