#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Maxiaofang_Attack04

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GA_Maxiaofang_Attack04.GA_Maxiaofang_Attack04_C.ExecuteUbergraph_GA_Maxiaofang_Attack04
// 0x0268 (0x0268 - 0x0000)
struct GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc__________;                                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________1;                              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc______________;                            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character;            // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________2;                              // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0060(0x0028)(ZeroConstructor)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_____GA______________;                     // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00A8(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________3;                              // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x00E8(0x0028)(ZeroConstructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x3];                                      // 0x0111(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc__________SpeedRatio;                      // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0118(0x0028)(ZeroConstructor)
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue; // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_14A[0x6];                                      // 0x014A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________4;                              // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________5;                              // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetWorldMoveDirectionCache_ReturnValue;   // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0168(0x0028)(ZeroConstructor)
	float                                         CallFunc_BreakVector2D_X;                          // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0198(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________6;                              // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B4[0x4];                                      // 0x01B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc____________;                              // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C2[0x2];                                      // 0x01C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x01C4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ATsBaseCharacter_C*                     CallFunc___________7;                              // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________1;                          // 0x01E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E5[0x3];                                      // 0x01E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x01EC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ATsBaseCharacter_C*                     CallFunc___________8;                              // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________9;                              // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetWorldMoveDirectionCache_ReturnValue_1; // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_1;                        // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_1;                        // 0x0214(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0218(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue_1;                      // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_2;             // 0x0228(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc________ReturnValue;                       // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23A[0x2];                                      // 0x023A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue_1;       // 0x023C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll_1;                      // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch_1;                     // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw_1;                       // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x0254(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc________ReturnValue_1;                     // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04) == 0x000008, "Wrong alignment on GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04");
static_assert(sizeof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04) == 0x000268, "Wrong size on GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, EntryPoint) == 0x000000, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetDisplayName_ReturnValue) == 0x000008, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc__________) == 0x000018, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc__________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________1) == 0x000020, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc______________) == 0x000028, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc______________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetOwningActorFromActorInfo_ReturnValue) == 0x000030, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetOwningActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_DynamicCast_AsTs_Base_Character) == 0x000038, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_DynamicCast_AsTs_Base_Character' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000044, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________2) == 0x000048, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________2' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetDisplayName_ReturnValue_1) == 0x000050, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_CreateDelegate_OutputDelegate) == 0x000060, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetObjectClass_ReturnValue) == 0x000088, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000090, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_____GA______________) == 0x000098, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_____GA______________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000A8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Conv_NameToString_ReturnValue) == 0x0000D0, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________3) == 0x0000E0, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________3' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000E8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_IsValid_ReturnValue) == 0x000110, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc__________SpeedRatio) == 0x000114, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc__________SpeedRatio' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_CreateDelegate_OutputDelegate_3) == 0x000118, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue) == 0x000140, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_IsValid_ReturnValue_1) == 0x000148, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_Event_bWasCancelled) == 0x000149, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________4) == 0x000150, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________4' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________5) == 0x000158, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________5' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetWorldMoveDirectionCache_ReturnValue) == 0x000160, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetWorldMoveDirectionCache_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, K2Node_CreateDelegate_OutputDelegate_4) == 0x000168, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakVector2D_X) == 0x000190, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakVector2D_Y) == 0x000194, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_MakeVector_ReturnValue) == 0x000198, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________6) == 0x0001A8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________6' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_VSize_ReturnValue) == 0x0001B0, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc____________) == 0x0001B8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc____________' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Greater_FloatFloat_ReturnValue) == 0x0001C0, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_IsValid_ReturnValue_2) == 0x0001C1, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x0001C4, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________7) == 0x0001D0, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________7' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakRotator_Roll) == 0x0001D8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakRotator_Pitch) == 0x0001DC, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakRotator_Yaw) == 0x0001E0, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_______________1) == 0x0001E4, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_______________1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Add_FloatFloat_ReturnValue) == 0x0001E8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_MakeRotator_ReturnValue) == 0x0001EC, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________8) == 0x0001F8, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________8' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc___________9) == 0x000200, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc___________9' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetWorldMoveDirectionCache_ReturnValue_1) == 0x000208, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetWorldMoveDirectionCache_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakVector2D_X_1) == 0x000210, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakVector2D_Y_1) == 0x000214, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_MakeVector_ReturnValue_1) == 0x000218, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_VSize_ReturnValue_1) == 0x000224, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_VSize_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_GetDisplayName_ReturnValue_2) == 0x000228, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_GetDisplayName_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000238, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc________ReturnValue) == 0x000239, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc________ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_Conv_VectorToRotator_ReturnValue_1) == 0x00023C, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_Conv_VectorToRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakRotator_Roll_1) == 0x000248, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakRotator_Roll_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakRotator_Pitch_1) == 0x00024C, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakRotator_Pitch_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_BreakRotator_Yaw_1) == 0x000250, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_BreakRotator_Yaw_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc_MakeRotator_ReturnValue_1) == 0x000254, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04, CallFunc________ReturnValue_1) == 0x000260, "Member 'GA_Maxiaofang_Attack04_C_ExecuteUbergraph_GA_Maxiaofang_Attack04::CallFunc________ReturnValue_1' has a wrong offset!");

// Function GA_Maxiaofang_Attack04.GA_Maxiaofang_Attack04_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_Maxiaofang_Attack04_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Maxiaofang_Attack04_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_Maxiaofang_Attack04_C_K2_OnEndAbility");
static_assert(sizeof(GA_Maxiaofang_Attack04_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_Maxiaofang_Attack04_C_K2_OnEndAbility");
static_assert(offsetof(GA_Maxiaofang_Attack04_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_Maxiaofang_Attack04_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

