#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Yangyang_UpAtk2_Rogue

#include "Basic.hpp"

#include "GA_Yangyang_UpAtk2_Rogue_classes.hpp"
#include "GA_Yangyang_UpAtk2_Rogue_parameters.hpp"


namespace SDK
{

// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.ExecuteUbergraph_GA_Yangyang_UpAtk2_Rogue
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Yangyang_UpAtk2_Rogue_C::ExecuteUbergraph_GA_Yangyang_UpAtk2_Rogue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "ExecuteUbergraph_GA_Yangyang_UpAtk2_Rogue");

	Params::GA_Yangyang_UpAtk2_Rogue_C_ExecuteUbergraph_GA_Yangyang_UpAtk2_Rogue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCompleted_5D118C384AE61F1C80292E8135E60225
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCompleted_5D118C384AE61F1C80292E8135E60225()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E8135E60225");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E8135E60225
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E8135E60225()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E8135E60225");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E8135E60225
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E8135E60225()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E8135E60225");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCancelled_5D118C384AE61F1C80292E8135E60225
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCancelled_5D118C384AE61F1C80292E8135E60225()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E8135E60225");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnTick_5D118C384AE61F1C80292E8135E60225
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnTick_5D118C384AE61F1C80292E8135E60225()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnTick_5D118C384AE61F1C80292E8135E60225");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.EventReceived_40E3832B4DE91E833946238DB940B866
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Yangyang_UpAtk2_Rogue_C::EventReceived_40E3832B4DE91E833946238DB940B866(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "EventReceived_40E3832B4DE91E833946238DB940B866");

	Params::GA_Yangyang_UpAtk2_Rogue_C_EventReceived_40E3832B4DE91E833946238DB940B866 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCompleted_5D118C384AE61F1C80292E812D53380B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCompleted_5D118C384AE61F1C80292E812D53380B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E812D53380B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E812D53380B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E812D53380B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E812D53380B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E812D53380B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E812D53380B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E812D53380B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCancelled_5D118C384AE61F1C80292E812D53380B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCancelled_5D118C384AE61F1C80292E812D53380B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E812D53380B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnTick_5D118C384AE61F1C80292E812D53380B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnTick_5D118C384AE61F1C80292E812D53380B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnTick_5D118C384AE61F1C80292E812D53380B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCompleted_5D118C384AE61F1C80292E813EB06145
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCompleted_5D118C384AE61F1C80292E813EB06145()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E813EB06145");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E813EB06145
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E813EB06145()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E813EB06145");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E813EB06145
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E813EB06145()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E813EB06145");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCancelled_5D118C384AE61F1C80292E813EB06145
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCancelled_5D118C384AE61F1C80292E813EB06145()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E813EB06145");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnTick_5D118C384AE61F1C80292E813EB06145
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnTick_5D118C384AE61F1C80292E813EB06145()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnTick_5D118C384AE61F1C80292E813EB06145");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCompleted_5D118C384AE61F1C80292E8147E35A8B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCompleted_5D118C384AE61F1C80292E8147E35A8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E8147E35A8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E8147E35A8B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E8147E35A8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E8147E35A8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E8147E35A8B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E8147E35A8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E8147E35A8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnCancelled_5D118C384AE61F1C80292E8147E35A8B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnCancelled_5D118C384AE61F1C80292E8147E35A8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E8147E35A8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_UpAtk2_Rogue.GA_Yangyang_UpAtk2_Rogue_C.OnTick_5D118C384AE61F1C80292E8147E35A8B
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_UpAtk2_Rogue_C::OnTick_5D118C384AE61F1C80292E8147E35A8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_UpAtk2_Rogue_C", "OnTick_5D118C384AE61F1C80292E8147E35A8B");

	UObject::ProcessEvent(Func, nullptr);
}

}

