#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Yangyang_UpAtk2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Yangyang_UpAtk2.GA_Yangyang_UpAtk2_C
// 0x0010 (0x0568 - 0x0558)
class UGA_Yangyang_UpAtk2_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Yangyang_UpAtk2_C;               // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          命中目标;                                          // 0x0560(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_GA_Yangyang_UpAtk2(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnCompleted_5D118C384AE61F1C80292E81843E23D7();
	void OnBlendOut_5D118C384AE61F1C80292E81843E23D7();
	void OnInterrupted_5D118C384AE61F1C80292E81843E23D7();
	void OnCancelled_5D118C384AE61F1C80292E81843E23D7();
	void OnTick_5D118C384AE61F1C80292E81843E23D7();
	void EventReceived_0B64479D48B35A6CD65F4FAEC1FC4D95(const struct FGameplayEventData& Payload);
	void OnCompleted_5D118C384AE61F1C80292E81CF542E50();
	void OnBlendOut_5D118C384AE61F1C80292E81CF542E50();
	void OnInterrupted_5D118C384AE61F1C80292E81CF542E50();
	void OnCancelled_5D118C384AE61F1C80292E81CF542E50();
	void OnTick_5D118C384AE61F1C80292E81CF542E50();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Yangyang_UpAtk2_C">();
	}
	static class UGA_Yangyang_UpAtk2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Yangyang_UpAtk2_C>();
	}
};
static_assert(alignof(UGA_Yangyang_UpAtk2_C) == 0x000008, "Wrong alignment on UGA_Yangyang_UpAtk2_C");
static_assert(sizeof(UGA_Yangyang_UpAtk2_C) == 0x000568, "Wrong size on UGA_Yangyang_UpAtk2_C");
static_assert(offsetof(UGA_Yangyang_UpAtk2_C, UberGraphFrame_GA_Yangyang_UpAtk2_C) == 0x000558, "Member 'UGA_Yangyang_UpAtk2_C::UberGraphFrame_GA_Yangyang_UpAtk2_C' has a wrong offset!");
static_assert(offsetof(UGA_Yangyang_UpAtk2_C, 命中目标) == 0x000560, "Member 'UGA_Yangyang_UpAtk2_C::命中目标' has a wrong offset!");

}

