#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Yangyang_Skill_Rogue

#include "Basic.hpp"

#include "GA_Yangyang_Skill_Rogue_classes.hpp"
#include "GA_Yangyang_Skill_Rogue_parameters.hpp"


namespace SDK
{

// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.ExecuteUbergraph_GA_Yangyang_Skill_Rogue
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Yangyang_Skill_Rogue_C::ExecuteUbergraph_GA_Yangyang_Skill_Rogue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "ExecuteUbergraph_GA_Yangyang_Skill_Rogue");

	Params::GA_Yangyang_Skill_Rogue_C_ExecuteUbergraph_GA_Yangyang_Skill_Rogue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCompleted_5D118C384AE61F1C80292E81023A9850
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCompleted_5D118C384AE61F1C80292E81023A9850()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E81023A9850");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E81023A9850
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E81023A9850()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E81023A9850");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E81023A9850
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E81023A9850()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E81023A9850");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCancelled_5D118C384AE61F1C80292E81023A9850
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCancelled_5D118C384AE61F1C80292E81023A9850()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E81023A9850");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnTick_5D118C384AE61F1C80292E81023A9850
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnTick_5D118C384AE61F1C80292E81023A9850()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnTick_5D118C384AE61F1C80292E81023A9850");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCompleted_5D118C384AE61F1C80292E81450FBA12
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCompleted_5D118C384AE61F1C80292E81450FBA12()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E81450FBA12");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E81450FBA12
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E81450FBA12()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E81450FBA12");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E81450FBA12
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E81450FBA12()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E81450FBA12");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCancelled_5D118C384AE61F1C80292E81450FBA12
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCancelled_5D118C384AE61F1C80292E81450FBA12()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E81450FBA12");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnTick_5D118C384AE61F1C80292E81450FBA12
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnTick_5D118C384AE61F1C80292E81450FBA12()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnTick_5D118C384AE61F1C80292E81450FBA12");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCompleted_5D118C384AE61F1C80292E81DE50AC49
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCompleted_5D118C384AE61F1C80292E81DE50AC49()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E81DE50AC49");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E81DE50AC49
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E81DE50AC49()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E81DE50AC49");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E81DE50AC49
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E81DE50AC49()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E81DE50AC49");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCancelled_5D118C384AE61F1C80292E81DE50AC49
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCancelled_5D118C384AE61F1C80292E81DE50AC49()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E81DE50AC49");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnTick_5D118C384AE61F1C80292E81DE50AC49
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnTick_5D118C384AE61F1C80292E81DE50AC49()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnTick_5D118C384AE61F1C80292E81DE50AC49");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCompleted_5D118C384AE61F1C80292E817C4F382F
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCompleted_5D118C384AE61F1C80292E817C4F382F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCompleted_5D118C384AE61F1C80292E817C4F382F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnBlendOut_5D118C384AE61F1C80292E817C4F382F
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnBlendOut_5D118C384AE61F1C80292E817C4F382F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnBlendOut_5D118C384AE61F1C80292E817C4F382F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnInterrupted_5D118C384AE61F1C80292E817C4F382F
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnInterrupted_5D118C384AE61F1C80292E817C4F382F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnInterrupted_5D118C384AE61F1C80292E817C4F382F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnCancelled_5D118C384AE61F1C80292E817C4F382F
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnCancelled_5D118C384AE61F1C80292E817C4F382F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnCancelled_5D118C384AE61F1C80292E817C4F382F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Yangyang_Skill_Rogue.GA_Yangyang_Skill_Rogue_C.OnTick_5D118C384AE61F1C80292E817C4F382F
// (BlueprintCallable, BlueprintEvent)

void UGA_Yangyang_Skill_Rogue_C::OnTick_5D118C384AE61F1C80292E817C4F382F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Yangyang_Skill_Rogue_C", "OnTick_5D118C384AE61F1C80292E817C4F382F");

	UObject::ProcessEvent(Func, nullptr);
}

}

