#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Yangyang_AirAttack_Rogue

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GA_Yangyang_AirAttack_Rogue.GA_Yangyang_AirAttack_Rogue_C.ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue
// 0x05D0 (0x05D0 - 0x0000)
struct GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc__________;                                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0028)(ZeroConstructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0028)(ZeroConstructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0060(0x0028)(ZeroConstructor)
	class UAbilityTask_WaitDelay*                 CallFunc_WaitDelay_ReturnValue;                    // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x2];                                       // 0x0092(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc__________SpeedRatio;                      // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0098(0x0028)(ZeroConstructor)
	class ATsBaseCharacter_C*                     CallFunc___________1;                              // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc______________;                            // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________2;                              // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________3;                              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________1;                          // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0100(0x0028)(ZeroConstructor)
	class UAnimMontage*                           CallFunc___________4;                              // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue; // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0160(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_____GA______________;                     // 0x0188(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0198(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x01C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________5;                              // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D9[0x3];                                      // 0x01D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc__________SpeedRatio_1;                    // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________6;                              // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________2;                          // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________7;                              // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________8;                              // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________3;                          // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_1; // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character_1;          // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_219[0x3];                                      // 0x0219(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x021C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0220(0x0028)(ZeroConstructor)
	class UAnimMontage*                           CallFunc___________9;                              // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_1; // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x0258(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_1;             // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue_1;      // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_279[0x7];                                      // 0x0279(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0280(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_____GA_______________1;                   // 0x02A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_9;            // 0x02B8(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue_1;          // 0x02E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_10;           // 0x02F0(0x0028)(ZeroConstructor)
	class UAnimMontage*                           CallFunc___________10;                             // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ___bool_Has_Been_Initd_Variable;                   // 0x0321(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_322[0x6];                                      // 0x0322(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_11;           // 0x0328(0x0028)(ZeroConstructor)
	float                                         CallFunc__________SpeedRatio_2;                    // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_354[0x4];                                      // 0x0354(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________11;                             // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________4;                          // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_361[0x7];                                      // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________12;                             // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________13;                             // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________5;                          // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_2; // 0x0380(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character_2;          // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_391[0x3];                                      // 0x0391(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_2;            // 0x0394(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_12;           // 0x0398(0x0028)(ZeroConstructor)
	class UAnimMontage*                           CallFunc___________14;                             // 0x03C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_2; // 0x03C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_2;             // 0x03D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E1[0x7];                                      // 0x03E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_2;             // 0x03E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue_2;      // 0x03F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F1[0x7];                                      // 0x03F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_____GA_______________2;                   // 0x03F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_13;           // 0x0408(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue_2;          // 0x0430(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_14;           // 0x0440(0x0028)(ZeroConstructor)
	class UAnimMontage*                           CallFunc___________15;                             // 0x0468(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0470(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0471(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_472[0x6];                                      // 0x0472(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________16;                             // 0x0478(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_15;           // 0x0480(0x0028)(ZeroConstructor)
	class ATsBaseCharacter_C*                     CallFunc___________17;                             // 0x04A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________6;                          // 0x04B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B1[0x7];                                      // 0x04B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________18;                             // 0x04B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________7;                          // 0x04C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C1[0x7];                                      // 0x04C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________19;                             // 0x04C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ___bool_IsClosed_Variable;                         // 0x04D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D1[0x7];                                      // 0x04D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVectorDouble                          CallFunc_D_GetActorUpVector_ReturnValue;           // 0x04D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue;       // 0x04F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________20;                             // 0x0508(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________21;                             // 0x0510(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_GetActorUpVector_ReturnValue_1;         // 0x0518(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue_1;     // 0x0530(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________22;                             // 0x0548(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________23;                             // 0x0550(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBuffCountById_ReturnValue;             // 0x0558(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x055C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55D[0x3];                                      // 0x055D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________24;                             // 0x0560(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0568(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_CreateBulletFromGA_ReturnValue;           // 0x0578(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57C[0x4];                                      // 0x057C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Kuro_GetBlockActorWhenMove_ReturnValue;   // 0x0580(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AStaticMeshActor*                       K2Node_DynamicCast_As_____actor;                   // 0x0588(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0590(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_591[0x3];                                      // 0x0591(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue;         // 0x0594(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0598(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59C[0x4];                                      // 0x059C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________25;                             // 0x05A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________26;                             // 0x05A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_CreateBulletFromGA_ReturnValue_1;         // 0x05B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_CreateBulletFromGA_ReturnValue_2;         // 0x05B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________27;                             // 0x05B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________28;                             // 0x05C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_CreateBulletFromGA_ReturnValue_3;         // 0x05C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_CreateBulletFromGA_ReturnValue_4;         // 0x05CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue) == 0x000008, "Wrong alignment on GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue");
static_assert(sizeof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue) == 0x0005D0, "Wrong size on GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, EntryPoint) == 0x000000, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc__________) == 0x000008, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc__________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_2) == 0x000060, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_WaitDelay_ReturnValue) == 0x000088, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_WaitDelay_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000090, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue) == 0x000091, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc__________SpeedRatio) == 0x000094, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc__________SpeedRatio' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_3) == 0x000098, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________1) == 0x0000C0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc______________) == 0x0000C8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc______________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________2) == 0x0000D0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________3) == 0x0000D8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________1) == 0x0000E0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetOwningActorFromActorInfo_ReturnValue) == 0x0000E8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetOwningActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_AsTs_Base_Character) == 0x0000F0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_AsTs_Base_Character' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_bSuccess) == 0x0000F8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_IntToFloat_ReturnValue) == 0x0000FC, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_4) == 0x000100, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________4) == 0x000128, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue) == 0x000130, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetDisplayName_ReturnValue) == 0x000138, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue_1) == 0x000148, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetObjectClass_ReturnValue) == 0x000150, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000158, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_5) == 0x000160, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_____GA______________) == 0x000188, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_____GA______________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_6) == 0x000198, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_NameToString_ReturnValue) == 0x0001C0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________5) == 0x0001D0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue_2) == 0x0001D8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc__________SpeedRatio_1) == 0x0001DC, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc__________SpeedRatio_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________6) == 0x0001E0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________6' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________2) == 0x0001E8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________7) == 0x0001F0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________7' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________8) == 0x0001F8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________8' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________3) == 0x000200, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetOwningActorFromActorInfo_ReturnValue_1) == 0x000208, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetOwningActorFromActorInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_AsTs_Base_Character_1) == 0x000210, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_AsTs_Base_Character_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_bSuccess_1) == 0x000218, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x00021C, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_7) == 0x000220, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________9) == 0x000248, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________9' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_1) == 0x000250, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetDisplayName_ReturnValue_1) == 0x000258, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue_3) == 0x000268, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetObjectClass_ReturnValue_1) == 0x000270, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetObjectClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_EqualEqual_ClassClass_ReturnValue_1) == 0x000278, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_EqualEqual_ClassClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_8) == 0x000280, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_____GA_______________1) == 0x0002A8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_____GA_______________1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_9) == 0x0002B8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_NameToString_ReturnValue_1) == 0x0002E0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_NameToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_10) == 0x0002F0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_10' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________10) == 0x000318, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________10' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue_4) == 0x000320, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, ___bool_Has_Been_Initd_Variable) == 0x000321, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::___bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_11) == 0x000328, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_11' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc__________SpeedRatio_2) == 0x000350, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc__________SpeedRatio_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________11) == 0x000358, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________11' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________4) == 0x000360, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________12) == 0x000368, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________12' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________13) == 0x000370, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________13' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________5) == 0x000378, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetOwningActorFromActorInfo_ReturnValue_2) == 0x000380, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetOwningActorFromActorInfo_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_AsTs_Base_Character_2) == 0x000388, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_AsTs_Base_Character_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_bSuccess_2) == 0x000390, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_IntToFloat_ReturnValue_2) == 0x000394, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_IntToFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_12) == 0x000398, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_12' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________14) == 0x0003C0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________14' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_2) == 0x0003C8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetDisplayName_ReturnValue_2) == 0x0003D0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetDisplayName_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue_5) == 0x0003E0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetObjectClass_ReturnValue_2) == 0x0003E8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetObjectClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_EqualEqual_ClassClass_ReturnValue_2) == 0x0003F0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_EqualEqual_ClassClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_____GA_______________2) == 0x0003F8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_____GA_______________2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_13) == 0x000408, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_13' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_NameToString_ReturnValue_2) == 0x000430, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_NameToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_14) == 0x000440, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_14' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________15) == 0x000468, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________15' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_IsValid_ReturnValue_6) == 0x000470, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_Event_bWasCancelled) == 0x000471, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________16) == 0x000478, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________16' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_CreateDelegate_OutputDelegate_15) == 0x000480, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_CreateDelegate_OutputDelegate_15' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________17) == 0x0004A8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________17' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________6) == 0x0004B0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________6' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________18) == 0x0004B8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________18' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_______________7) == 0x0004C0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_______________7' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________19) == 0x0004C8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________19' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, ___bool_IsClosed_Variable) == 0x0004D0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::___bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_D_GetActorUpVector_ReturnValue) == 0x0004D8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_D_GetActorUpVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_D_Multiply_VectorFloat_ReturnValue) == 0x0004F0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_D_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________20) == 0x000508, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________20' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________21) == 0x000510, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________21' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_D_GetActorUpVector_ReturnValue_1) == 0x000518, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_D_GetActorUpVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_D_Multiply_VectorFloat_ReturnValue_1) == 0x000530, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_D_Multiply_VectorFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________22) == 0x000548, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________22' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________23) == 0x000550, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________23' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetBuffCountById_ReturnValue) == 0x000558, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetBuffCountById_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_SwitchInteger_CmpSuccess) == 0x00055C, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________24) == 0x000560, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________24' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Conv_IntToString_ReturnValue) == 0x000568, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreateBulletFromGA_ReturnValue) == 0x000578, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreateBulletFromGA_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Kuro_GetBlockActorWhenMove_ReturnValue) == 0x000580, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Kuro_GetBlockActorWhenMove_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_As_____actor) == 0x000588, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_As_____actor' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, K2Node_DynamicCast_bSuccess_3) == 0x000590, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_GetWorldDeltaSeconds_ReturnValue) == 0x000594, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_GetWorldDeltaSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_Add_FloatFloat_ReturnValue) == 0x000598, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________25) == 0x0005A0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________25' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________26) == 0x0005A8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________26' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreateBulletFromGA_ReturnValue_1) == 0x0005B0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreateBulletFromGA_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreateBulletFromGA_ReturnValue_2) == 0x0005B4, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreateBulletFromGA_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________27) == 0x0005B8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________27' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc___________28) == 0x0005C0, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc___________28' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreateBulletFromGA_ReturnValue_3) == 0x0005C8, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreateBulletFromGA_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue, CallFunc_CreateBulletFromGA_ReturnValue_4) == 0x0005CC, "Member 'GA_Yangyang_AirAttack_Rogue_C_ExecuteUbergraph_GA_Yangyang_AirAttack_Rogue::CallFunc_CreateBulletFromGA_ReturnValue_4' has a wrong offset!");

// Function GA_Yangyang_AirAttack_Rogue.GA_Yangyang_AirAttack_Rogue_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility");
static_assert(sizeof(GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility");
static_assert(offsetof(GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_Yangyang_AirAttack_Rogue_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

