#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Yangyang_XuliAttack

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_Yangyang_XuliAttack.GA_Yangyang_XuliAttack_C.ExecuteUbergraph_GA_Yangyang_XuliAttack
// 0x02A8 (0x02A8 - 0x0000)
struct GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc__________;                                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0028)(ZeroConstructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0028)(ZeroConstructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0060(0x0028)(ZeroConstructor)
	class UAbilityTask_WaitDelay*                 CallFunc_WaitDelay_ReturnValue;                    // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0090(0x0028)(ZeroConstructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_WaitDelay*                 CallFunc_WaitDelay_ReturnValue_1;                  // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________1;                              // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________2;                              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc______________;                            // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0100(0x0028)(ZeroConstructor)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc___________3;                              // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0148(0x0028)(ZeroConstructor)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0180(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x01A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_____GA______________;                     // 0x01B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________4;                              // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x3];                                      // 0x01D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc__________SpeedRatio;                      // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue; // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E2[0x6];                                      // 0x01E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________5;                              // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc____________;                              // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x01F8(0x0028)(ZeroConstructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_221[0x3];                                      // 0x0221(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc________ReturnValue;                       // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_229[0x3];                                      // 0x0229(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc___________2D_____;                        // 0x022C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0238(0x0028)(ZeroConstructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________6;                              // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTaskOwnerInterface> CallFunc_TaskWaitDelay_TaskOwner_CastInput;  // 0x0270(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	class UGameplayTask_WaitDelay*                CallFunc_TaskWaitDelay_ReturnValue;                // 0x0280(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________1;                          // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0289(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_28A[0x6];                                      // 0x028A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________7;                              // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_299[0x3];                                      // 0x0299(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x029C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A1[0x3];                                      // 0x02A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_FClamp_ReturnValue;                       // 0x02A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack) == 0x000008, "Wrong alignment on GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack");
static_assert(sizeof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack) == 0x0002A8, "Wrong size on GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, EntryPoint) == 0x000000, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc__________) == 0x000008, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc__________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_2) == 0x000060, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_WaitDelay_ReturnValue) == 0x000088, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_WaitDelay_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_3) == 0x000090, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_IsValid_ReturnValue) == 0x0000B8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_WaitDelay_ReturnValue_1) == 0x0000C0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_WaitDelay_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_IsValid_ReturnValue_1) == 0x0000C8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________1) == 0x0000D0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________2) == 0x0000D8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc______________) == 0x0000E0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc______________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_GetOwningActorFromActorInfo_ReturnValue) == 0x0000E8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_GetOwningActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_DynamicCast_AsTs_Base_Character) == 0x0000F0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_DynamicCast_AsTs_Base_Character' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_DynamicCast_bSuccess) == 0x0000F8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_4) == 0x000100, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000128, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________3) == 0x000130, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_GetDisplayName_ReturnValue) == 0x000138, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_5) == 0x000148, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_GetObjectClass_ReturnValue) == 0x000170, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000178, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_6) == 0x000180, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_Conv_NameToString_ReturnValue) == 0x0001A8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_____GA______________) == 0x0001B8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_____GA______________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________4) == 0x0001C8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_IsValid_ReturnValue_2) == 0x0001D0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc__________SpeedRatio) == 0x0001D4, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc__________SpeedRatio' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue) == 0x0001D8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_IsValid_ReturnValue_3) == 0x0001E0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_Event_bWasCancelled) == 0x0001E1, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________5) == 0x0001E8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc____________) == 0x0001F0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc____________' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_7) == 0x0001F8, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_IsValid_ReturnValue_4) == 0x000220, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc________ReturnValue) == 0x000224, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc________ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000228, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________2D_____) == 0x00022C, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________2D_____' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000230, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, K2Node_CreateDelegate_OutputDelegate_8) == 0x000238, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_BooleanAND_ReturnValue) == 0x000260, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________6) == 0x000268, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________6' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_TaskWaitDelay_TaskOwner_CastInput) == 0x000270, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_TaskWaitDelay_TaskOwner_CastInput' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_TaskWaitDelay_ReturnValue) == 0x000280, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_TaskWaitDelay_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_______________1) == 0x000288, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_______________1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_IsValid_ReturnValue_5) == 0x000289, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc___________7) == 0x000290, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc___________7' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_Not_PreBool_ReturnValue) == 0x000298, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x00029C, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_BooleanAND_ReturnValue_1) == 0x0002A0, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack, CallFunc_FClamp_ReturnValue) == 0x0002A4, "Member 'GA_Yangyang_XuliAttack_C_ExecuteUbergraph_GA_Yangyang_XuliAttack::CallFunc_FClamp_ReturnValue' has a wrong offset!");

// Function GA_Yangyang_XuliAttack.GA_Yangyang_XuliAttack_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_Yangyang_XuliAttack_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Yangyang_XuliAttack_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_Yangyang_XuliAttack_C_K2_OnEndAbility");
static_assert(sizeof(GA_Yangyang_XuliAttack_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_Yangyang_XuliAttack_C_K2_OnEndAbility");
static_assert(offsetof(GA_Yangyang_XuliAttack_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_Yangyang_XuliAttack_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

