#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateSetCollisionLv

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateSetCollisionLv.TsAnimNotifyStateSetCollisionLv_C
// 0x0008 (0x0050 - 0x0048)
class UTsAnimNotifyStateSetCollisionLv_C final : public UKuroAnimNotifyState
{
public:
	int32                                         HitPriority;                                       // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TsAnimNotifyStateSetCollisionLv_C">();
	}
	static class UTsAnimNotifyStateSetCollisionLv_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateSetCollisionLv_C>();
	}
};
static_assert(alignof(UTsAnimNotifyStateSetCollisionLv_C) == 0x000008, "Wrong alignment on UTsAnimNotifyStateSetCollisionLv_C");
static_assert(sizeof(UTsAnimNotifyStateSetCollisionLv_C) == 0x000050, "Wrong size on UTsAnimNotifyStateSetCollisionLv_C");
static_assert(offsetof(UTsAnimNotifyStateSetCollisionLv_C, HitPriority) == 0x000048, "Member 'UTsAnimNotifyStateSetCollisionLv_C::HitPriority' has a wrong offset!");

}

